- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtil.java
- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WindupWebServiceFactory.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/WindupWebServiceFactoryImpl.java
- furnace-service-provider/pom.xml
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FromFurnace.java
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FurnaceExtension.java
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FurnaceProducer.java
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FurnaceShutdownEvent.java
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/WebProperties.java
- furnace-service-provider/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- pom.xml
- services/pom.xml
- services/src/main/java/org/jboss/windup/web/services/producer/WindupServicesProducer.java
- services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/servlet/FileDefaultServlet.java
- services/src/test/java/org/jboss/windup/web/services/AbstractTest.java
- services/src/test/java/org/jboss/windup/web/services/ServerCleanupOnStartup.java
- services/src/test/java/org/jboss/windup/web/services/servlet/FileDefaultServletTest.java
- ui/src/test/java/org/jboss/windup/web/ui/AbstractUITest.java
- ui/src/test/resources/WEB-INF/classes/windupweb.properties
- ui/src/test/resources/arquillian.xml
@gastaldi @OndraZizka @mareknovotny 
Please take a look... it seems to work for my basic tests. At the moment it works with no qualifiers, but I have been thinking of making it only look in Furnace if a @FromFurnace qualifier is applied at the injection site. What do you think?
Also, feel free to point any the other issues. Obviously the spurious printlns need to be cleaned up (yes, I should have used a Logger).
> Added a bridge to enable communication from the Furnace environment to the CDI environment in the webapp, without duplicated producer methods.

- services/src/main/webapp/WEB-INF/web.xml
According to https://issues.jboss.org/browse/JBEAP-3669 , this should reveal the resteasy stats at /windup-web-services/resteasy/registry .  But it doesn't work for me. Did anyone see this ever working? It would come in handy for me.
> List endpoints - windup-web-services/resteasy/registry

- services/src/main/java/org/jboss/windup/web/services/rest/RestApplication.java
- services/src/main/java/org/jboss/windup/web/services/rest/graph/AbstractGraphResource.java
- services/src/main/java/org/jboss/windup/web/services/rest/graph/FileModelResourceImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/graph/GraphResource.java
- services/src/main/java/org/jboss/windup/web/services/rest/graph/GraphResourceImpl.java
- services/src/test/java/org/jboss/windup/web/services/rest/graph/FileResourceTest.java
- services/src/test/java/org/jboss/windup/web/services/rest/graph/GraphResourceTest.java
- ui/src/main/webapp/app/services/graph/base.model.ts
- ui/src/main/webapp/app/services/graph/graph-adjacency.decorator.ts
- ui/src/main/webapp/app/services/graph/graph-json-to-model.service.ts
- ui/src/main/webapp/app/services/graph/graph-property.decorator.ts
- ui/src/main/webapp/tests/app/models/test-graph-data.ts
- ui/src/main/webapp/tests/app/models/test.models.ts
- ui/src/main/webapp/tests/app/unmarshaller.spec.ts
- ui/src/main/webapp/tests/unit-tests.html.ftl
This is an extension of the format that was already in master. A couple of notes:
- The vertices format has been changed, to make it clearer that all related vertices can be loaded at once
- The client code has been updated to be able to lazy load related data
- The client test has been updated with examples of lazy loaded data (mock data)
The generator (https://github.com/windup/windup-web/pull/64) will need to be updated to emit this format.
> Started work on returning links properly

- ui/src/main/webapp/package.json
For now webpack version must be beta.25
They made some backward incompatible changes in 26 causing compilation issues.
For more details see: https://github.com/webpack/webpack/issues/3296
> Set webpack version to beta.25.

- services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java
Fixed by moving the check for whether an app was uploaded into the helper method that deletes the app file.
> WINDUP-1238 -- unregistering app should only delete file if it was uploaded

- services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java
- services/src/main/java/org/jboss/windup/web/services/model/PackageMetadata.java
- services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java
- services/src/main/java/org/jboss/windup/web/services/rest/ForgeProxyMarshaller.java
- services/src/main/java/org/jboss/windup/web/services/service/PackageService.java
- services/src/test/java/org/jboss/windup/web/services/rest/ApplicationGroupTest.java
- ui/src/main/webapp/src/app/components/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/components/layout/group-layout.component.ts
- ui/src/main/webapp/src/app/components/navigation/context-menu-item.class.ts
- ui/src/main/webapp/src/app/services/application-group.service.ts
- No longer preload package information along with group lists. Now use a separate service call to get this information for the analysis context form.
- With larger applications, this can cost megabytes over the wire and result in multisecond delays in the UI
- No longer display the "Run Windup" option on the context sensitive menu if there are no registered applications.
> Fixed performance issues and minor cosmetic issues.

- services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java
- services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java
- services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/service/AnalysisContextService.java
- services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java
- services/src/test/java/org/jboss/windup/web/services/rest/ApplicationGroupTest.java
We had a bug which caused analysis context not being properly set for user created groups. 
It was set for Default Group, because this one was handled differently. 
For all other groups, it was created at the time of execution. But property ApplicationGroup on AnalysisContext was not set. So any time ApplicationGroup was fetched from entityManager, it didn't have any AnalysisContext. And for each execution, it would create new one again and again...
AnalysisContext should not be created without ApplicationGroup.
> Fix analysis context not being properly set for user created groups.

- ui/src/main/webapp/css/windup-web.css
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/app.routing.ts
- ui/src/main/webapp/src/app/components/group-list.component.html
- ui/src/main/webapp/src/app/components/layout/group-layout.component.ts
- ui/src/main/webapp/src/app/components/navbar.component.html
- ui/src/main/webapp/src/app/components/navigation/breadcrumbs-link.interface.ts
- ui/src/main/webapp/src/app/components/navigation/breadcrumbs.component.html
- ui/src/main/webapp/src/app/components/navigation/breadcrumbs.component.ts
- ui/src/main/webapp/src/app/components/navigation/breadcrumbs.service.ts
- ui/src/main/webapp/src/app/components/navigation/context-menu-item.class.ts
- ui/src/main/webapp/src/app/services/route-flattener.service.ts
What looked quite simple at the beginning, ended up being quite complex...
There are several problems with Angular 2 router, most significant ones are: 
- `params` and `data` from parent routes are not inherited
- `ActivatedRouteSnapshot` provided to components is different for each level of component based on its position in router-outlet hierarchy
These are solved by `RouteFlattenerService`. This service gets ActivatedRouteSnapshot and traverses its hierarchy up and down and merges required data. It should give the same results independently on current component's placement in hierarchy.
Another non trivial thing is to create breadcrumb links for meaningful parts of URL.
For example:
For given route
`/groups/15/reports/21/migration-issues`
meaningful breadcrumbs are: 
`/groups/15` …
> 364 breadcrumbs

- services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpoint.java
- services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpointImpl.java
- ui/src/main/webapp/src/app/components/configuration.component.html
- ui/src/main/webapp/src/app/components/configuration.component.ts
- ui/src/main/webapp/src/app/services/configuration.service.ts
I think it would be helpful to have some endpoint which would reload configuration. 
Right now it is reloaded automatically every 12 minutes, but sometimes you need to reload it right away. 
I'm not sure where to put it in UI, maybe somewhere into settings.
What do you think @jsight ?
> Add endpoint to force configuration reload.

- services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java
- services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java
- services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/ReportFilterEndpoint.java
- services/src/main/java/org/jboss/windup/web/services/rest/ReportFilterEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/service/ApplicationGroupService.java
- services/src/test/java/org/jboss/windup/web/services/rest/ApplicationGroupTest.java
I found bug in ApplicationGroup edit/delete. 
It was impossible to edit/delete group, because related entities were set to Cascade All and frontend didn't have properly set parents in child entities. (ReportFilter was missing ApplicationGroup and so on...).
We didn't have any tests for it, so I added some.
> Fix group edit

- services/src/main/java/org/jboss/windup/web/services/rest/UnhandledExceptionHandler.java
This PR was initially part of https://github.com/windup/windup-web/pull/117 but I would like to get it merged before, because I think it is quite useful. 
-----
Currently when there is unhandled exception server returns HTML page with stack trace and HTTP code 500. Angular tries to convert response to JSON which fails and it results into
- displaying a red error popup: "Error: Unknown error: undefined"
- following errors in console:
> abtract.service.ts:10 Service error: (object) SyntaxError: Unexpected end of JSON input
> abtract.service.ts:18 Service error - can't JSON: error.json is not a function 
I created global exception handler.
It should handle all exceptions and prevent server from returning HTML page with stack trace. Instead it will return proper JSON response with "Internal …
> Backend error handling

- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphCache.java
- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FurnacePreShutdownEvent.java
This relies on a change to windup core here: https://github.com/windup/windup/commit/1fbdac05a1cb6c217b06c03b1a9a08f899ce45fb
Basically the shutdown works, but some furnace operations cannot be relied on during the process.
> Better handling of the shutdown process

- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResourceImpl.java
- services/src/test/java/org/jboss/windup/web/services/rest/graph/GraphResourceTest.java
Usage:
Limit OUT edges to "knows": .../rest-furnace/graph/77/by-type/SourceReportModel?depth=1&out=knows
Disable in vertices: .../rest-furnace/graph/77/by-type/SourceReportModel?depth=1&in=x
> GraphResource - use edges whitelists in REST endpoint

- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpointImpl.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/AbstractGraphResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResourceImpl.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/ProjectTraversalResourceImpl.java
- services/src/test/java/org/jboss/windup/web/services/rest/graph/GraphResourceTest.java
the client will have to cache.
The deduplication is optional - @PathParam("dedup") @DefaultValue("false") boolean dedup
> Graph REST API - don't repeat already marshalled vertices 

- ui/src/main/webapp/src/app/components/edit-application-form.component.ts
ApplicationGroup property was not properly initialized. Use parent ngOnInit to initialize it.
> Fix cancel() button for application edit form.

- services/src/main/java/org/jboss/windup/web/services/rest/FileEndpointImpl.java
remoteUserCanQueryPath should not return false, if given path is pointing to file instead of directory.
User can register both - application file or directory containing multiple applications.
> Fix FileEndpoint.

- ui/src/main/webapp/src/app/components/analysis-context-form.component.html
- ui/src/main/webapp/src/app/components/analysis-context-form.component.ts
Previously there was the same action on save button and form submit, so the action was actually triggered twice.
It lead to server error caused by concurrent modification.
(after first change, analysis context version is incremented, but the second update was triggered with previous version number).
> Fix analysis context form submit.

- services/pom.xml
This saves quite some time in services rebuild.
> Skip the WF unpack if -DskipTests is set.

- ui/src/main/webapp/config/webpack.common.js
- ui/src/main/webapp/config/webpack.dev.js
- ui/src/main/webapp/config/webpack.prod.js
I noticed build is significantly slower when using AOT and it also doesn't contain certain debug information which are handy for example for Augury browser extension. I think for dev mode it is better not to use AOT.
> Update webpack config - use AOT only for production.

- ui/src/main/webapp/package.json
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/components/package-chart/package-chart.component.ts
- ui/src/main/webapp/src/app/components/reports/application-details/application-details.component.html
- ui/src/main/webapp/yarn.lock
I looked at this for much of the day, and had no luck figuring out why the height and width can no longer be calculated correctly by ngx-charts. I just hardcoded them.
Feel free to fix this if you have better luck than I did.
> Upgraded to ngx-charts 4.1.3 -- Hardcoded H*W, as it didn't work otherwise

- services/pom.xml
Not sure about the hibernate-jpamodelgen which should also be 5.0.10
See https://github.com/wildfly/boms/blob/wildfly-javaee7-10.1.0.Final/pom.xml
> Sync versions with WF

- ui/src/main/webapp/src/app/components/layout/group-layout.component.ts
I tried to disable it only for production environment, but there are some issues with AOT which seems not to be working right now.
This is just temporary solution until AOT is fixed.
> Do not show Technologies and Dependencies reports in navigation.

- ui/src/main/webapp/config/webpack.test.js
It seems it is not possible to skip evaluation of styles. null-loader doesn't fill in any value, but angular expects styles to be string array. It seems it is required to use loaders even for tests.
> Update webpack test configuration - add scss.

- ui/src/main/webapp/src/app/shared/navigation/navbar.component.html
- ui/src/main/webapp/src/app/shared/navigation/navbar.component.ts
Navbar is being redrawn on certain pages. I'm not sure about the reason. Angular change detector runs `isLinkActive` method many times and completely unnecessarily. I changed that to use Angular way of detecting if link is active. It seems to reduce redrawing at least for certain pages. But the main issue still needs to be fixed. (Unfortunately it might be something completely unrelated).
(Note: If we don't manage to merge before modules, I will rebase, this doesn't have to block modules)
> Update navbar - change link isActive method.

- ui/src/main/webapp/src/app/executions/executions-monitoring.component.ts
- ui/src/main/webapp/src/app/executions/project-executions.component.ts
I noticed that the list doesn't always update when running windup. This seems to fix it.
> Always update execution list when an execution is active

- ui/src/main/webapp/src/app/shared/checkboxes.component.html
- ui/src/main/webapp/src/app/shared/checkboxes.component.ts
- ui/src/main/webapp/tests/app/components/checkboxes.component.spec.ts
I wanted to simplify checkboxes component, but as I can see, @jsight has already done it in his PR https://github.com/windup/windup-web/pull/254 :)
Anyway, I added several things:
- Default values for callbacks (simplifies usage of component)
- Checks for input values 
- Tests
- Fixed returned items when valueCallback was used
> Simplify checkboxes component

- services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java
- services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java
- ui/src/main/webapp/src/app/registered-application/application-list.component.html
- ui/src/main/webapp/src/app/registered-application/application-list.component.ts
Taiga task 618 - deleting application was causing FK Constraint violations.
Now application entity is deleted if it is not used in any AnalysisContext. If it is used in AnalysisContext, flag `isDeleted` is set to `true`.This  "partially deleted" entity is kept in database to enable listing it in older reports.
> 618 delete application

- ui/src/main/webapp/src/app/components/app.component.ts
- ui/src/main/webapp/src/app/core/routing/route-flattener.service.ts
- ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts
- ui/src/main/webapp/src/app/shared/routed.component.ts
- ui/src/main/webapp/tests/app/components/reports/application-index/application-index.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
Taiga task #516 - Clicking on individual issue in issues report returns unhelpful error.
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/616
Actual problem was caused by multiple components subscribing to router
navigationEnd event and consuming that event. Solution is to subscribe
only in AppComponent and provide data to other components by using
shared service - RouteFlattenerService in this case.
Also ReplaySubject rather than Subject must be used - if component
subscribes after event was trigger, it wouldn't get any data.
ReplaySubject(1) will hold data to 1 step back and provide current
data to components subscribing later then event actually happened.
> Fix migration issues table

- ui/src/main/webapp/src/app/components/app.component.ts
- ui/src/main/webapp/src/app/core/routing/route-flattener.service.ts
- ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts
- ui/src/main/webapp/src/app/shared/routed.component.ts
- ui/src/main/webapp/tests/app/components/reports/application-index/application-index.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
Reverts windup/windup-web#274
There is an issue with `ReplaySubject` - it will trigger event for initial navigation. But that one doesn't have required data available. Using `Subject` is not a valid solution either, because components subscribing later won't get any data.
I need to think it through little bit more.
> Revert "Fix migration issues table"

- ui/src/main/webapp/src/app/components/app.component.ts
- ui/src/main/webapp/src/app/core/routing/route-flattener.service.ts
- ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts
- ui/src/main/webapp/src/app/shared/routed.component.ts
- ui/src/main/webapp/tests/app/components/reports/application-index/application-index.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts
- ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
I found (hopefully) proper fix for those problems with wizard (and probably not only wizard..).
Using `ReplaySubject` was mistake, it caused more problems then it solved.
Better solution is to use just `Subject` and use `ActivatedRoute.snapshot` in `OnInit` code prior to subscribing to `RouteFlattener OnFlatRouteLoaded`
event.
(I hope it won't break anything this time :) )
> 616 - migration issues bug (once again :) )

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html
- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/analysis-context/select-applications.component.html
- ui/src/main/webapp/src/app/analysis-context/select-applications.component.ts
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
- ui/src/main/webapp/src/app/shared/chosen/chosen-multiple.component.ts
This changes the process of configuring Windup to allow for easier selection of applications.
> Task 572: Configuration Page (settings and kick off windup)

- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu-link.component.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.ts
Currently items in ContextMenu don't have any real link, they have click action which triggers either routing or some action.
Having actual link on items is more user friendly, since it provides option to use 'wheel click'.
User can click with mouse wheel or use ctrl-click and open link in new tab. Also link can be copied.
ContextMenuLink component will handle click actions when defined, or provide [routerLink] with URL, if item has some.
<s>Right now I'm fighting with some angular issues which I would like to resolve first. I would ideally want to use directive which would apply angular default `[routerLink]` but this doesn't work :(  I created [StackOverflow post](http://stackoverflow.com/questions/42696413/angular-custom-routerlink-directive)   so let's see if anyone could help with …
> Create ContextMenuLink component

- ui/src/main/webapp/config/webpack.common.js
The extracttextloader should not be used for Angular CSS. However, the ngx-charts dependency was being
loaded by it. This change makes these css files be loaded by the raw-loader, which appears to work.
> Fix production Angular build

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/analysis-context/custom-rule-selection.component.ts
- ui/src/main/webapp/src/app/components/in-viewport.directive.ts
- ui/src/main/webapp/src/app/components/login.component.ts
- ui/src/main/webapp/src/app/configuration/configuration.component.ts
- ui/src/main/webapp/src/app/core/authentication/keycloak.service.ts
- ui/src/main/webapp/src/app/core/authentication/windup.http.service.ts
- ui/src/main/webapp/src/app/core/events/event-bus.service.ts
- ui/src/main/webapp/src/app/project/migration-project-form.component.ts
- ui/src/main/webapp/src/app/project/project-list.component.ts
- ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
- ui/src/main/webapp/src/app/reports/dependencies/dependencies-graph.component.ts
- ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts
- ui/src/main/webapp/src/app/reports/pretty-path.pipe.ts
- ui/src/main/webapp/src/app/reports/technologies/technologies-report.component.ts
- ui/src/main/webapp/src/app/services/graph/cache.ts
- ui/src/main/webapp/src/app/services/graph/graph-adjacency.decorator.ts
- ui/src/main/webapp/src/app/services/graph/graph-json-to-model.service.ts
- ui/src/main/webapp/src/app/shared/cache.service.ts
- ui/src/main/webapp/src/app/shared/confirm-deactivate.guard.ts
- ui/src/main/webapp/src/app/shared/form.component.ts
- ui/src/main/webapp/src/app/shared/popover.component.ts
- ui/src/main/webapp/src/app/shared/sort/sortable-table.component.ts
- ui/src/main/webapp/tests/app/components/shared/sortable-table.component.spec.ts
- ui/src/main/webapp/tests/app/generated-ts-files.spec.ts
- ui/src/main/webapp/tests/app/mocks/activated-route.mock.ts
- ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts
- ui/src/main/webapp/tests/app/services/cache/cache.decorator.spec.ts
- ui/src/main/webapp/tests/app/services/graph-cache-service.spec.ts
- ui/src/main/webapp/tests/app/unmarshaller.spec.ts
It is OK to use `console.log` for quick debugging while development,
but I think we should remove it when feature is finished. We had
quite a lot of logging in code and console became quite messy.
I removed most of  `console.log` statements and kept there only `warn` or
`error` ones, because these signal something wrong is going on and
should not get triggered in common use.
> Remove excessive logging

- ui/src/main/webapp/src/app/analysis-context/migration-path.service.ts
- ui/src/main/webapp/src/app/configuration/configuration-options.service.ts
- ui/src/main/webapp/src/app/configuration/configuration.service.ts
- ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
- ui/src/main/webapp/src/app/services/windup.service.ts
- ui/src/main/webapp/src/app/shared/cache.service.ts
- ui/src/main/webapp/tests/app/services/cache/cache.decorator.spec.ts
Add `cacheItemCallback` to `@Cached` decorator
Callback is used to determine if item can be cached. Result from function call is passed to callback and if it returns true, it is cached. Otherwise not.
It is useful for situations when certain object can be cached when it is in some specific state (for example `PackageMetadata` can be cached when `scanStatus` is `"COMPLETE"`).
> Improve cache

- ui/src/main/webapp/css/windup-web.css
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/app.routing.ts
- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.scss
- ui/src/main/webapp/src/app/executions/executions-layout.component.ts
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/project/project-layout.component.ts
- ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.html
- ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu-link.component.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
- ui/src/main/webapp/src/app/shared/sort/sorting.service.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
This page will supersede the execution details as the default page for executions.
Clicking on the leftmost column in the execution list will still take you to execution
details.
This still needs points, tags, and other details.
> Added an application list as the default report page.

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/executions/project-executions.component.ts
Update AnalysisContextForm - use the right service and method to start
execution. WindupExecutionService.execute methods triggers execution,
fires proper event and watches for changes.
Use ReplaySubject(3) in EventBusService. Components registering for
events after navigation wouldn't get any if Subject was used. 3 events
back seems to be reasonable size of history for this purpose.
> Fix active execution monitoring

- services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java
- services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java
- services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpoint.java
- services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpoint.java
- services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/service/AnalysisContextService.java
- services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java
- services/src/test/java/org/jboss/windup/web/services/data/DataProvider.java
- services/src/test/java/org/jboss/windup/web/services/data/WindupExecutionUtil.java
- services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java
- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/analysis-context/analysis-context.service.ts
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/services/windup-execution.service.ts
- ui/src/main/webapp/src/app/services/windup.service.ts
- ui/src/main/webapp/src/app/shared/cache.service.ts
Each project should have defaultAnalysisContext. This context is used
for configuration. It is never used for execution. Execution creates
a clone of that AnalysisContext.
There is fallback solution if defaultAnalysisContext doesn't exist on
MigrationProject (even though this should never happen!). Also
analysisContext should never be updated, when it is used for execution.
> Save analysis context - simpler solution

- ui/src/main/webapp/src/app/executions/executions-list.component.html
Replaced  'Executions' to 'Analysis' in component:
- heading h2
- table header
All the ids where "executions" is used have not been changed (e.g. "activeExecutions", "sortedExecutions").
> T712-Executions page: change 'Executions' to 'Analysis'

- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.ts
- ui/src/main/webapp/src/app/executions/project-executions.component.ts
- ui/src/main/webapp/src/app/shared/pretty-execution-state.pipe.ts
- ui/src/main/webapp/src/app/shared/utils.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
- Link to the Static Reports Instead of Dynamic Reports
- Combine duration with the "Status" column
- Fix state bugs adding "runUpdate" boolean variable to do the update only the first time the state changes from queued to started
- Change current word "STARTED" for state to "In Progress" adding a humanReadableLabel(state: ExecutionState) that translates state in labels in utils.ts and also changed all the label to not be "screamed" in capital letters
I had to wrap humanReadableLabel(state: ExecutionState) from utils.ts in executions-list.component.ts to make it usable in executions-list.component.html: is it right?
> T765_718_720-Executions Page: fix state bug and renamings

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
- commented the "Available Reports" tab waiting for dynamic report to be available
- renamed all "Executions" in "Analysis"
After commit https://github.com/mrizzi/windup-web/commit/9b55e440c44871474f38e949b94cc22955140243
- added handling of "CANCELLED" state to executions-list.component.html 
- fix tests
> T722_770 Execution Details Page: commented Reports tab and renaming

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/project/project.resolve.ts
Possible fix for: https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/773?kanban-status=543761
> Task 773: Bug when create a new project after a project deletion

- ui/src/main/webapp/src/app/project/project-list.component.html
- ui/src/main/webapp/src/app/project/project-list.component.ts
- ui/src/main/webapp/src/app/shared/confirmation-modal.component.html
- ui/src/main/webapp/src/app/shared/confirmation-modal.component.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Fixes issues with project delete dialog from #310
- cleans dialog after closing
- uses 1 dialog for all projects
- uses correct angular 2 bindings
> Fix project delete dialog

- services/src/main/java/org/jboss/windup/web/services/model/AdvancedOption.java
- services/src/main/java/org/jboss/windup/web/services/service/AnalysisContextService.java
Implemented the method to add the advanced option when a new analysis is executed, just like it is done for rules path and packages.
> T779 fix for adding advanced options with 'Save & Run'

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.ts
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Redesign for the analysis details page:
- new layout for data presentation (see mockup, slide 22)
- collapse/expand section for {in,ex}cluded packages
- dedicated tab for advanced options
- little change in analysis list (introduction of "#" sign before analysis id)
- tests updated
> T775 Analysis details page redesign

- services/src/main/java/org/jboss/windup/web/services/DataBackup.java
- services/src/main/java/org/jboss/windup/web/services/RuleDataLoader.java
- services/src/main/java/org/jboss/windup/web/services/model/RuleProviderEntity.java
- services/src/main/resources/META-INF/persistence.xml
- services/src/test/resources/META-INF/persistence-inmemory.xml
- services/src/test/resources/META-INF/persistence-ondisk.xml
This creates automatic backups of the db every 6 hours. It will keep 3 days
of these backups in a backup folder underneat the global Windup data folder.
Also, this makes sure to clean up any dangling rule entity objects. Previously
these were causing the database to grow in size, almost without bound.
> Autobackup and ruleentity cleanup

- ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/project/no-projects-welcome.component.html
- Configuration: Advanced options: "Delete" button L&F like "Add" [#843](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/843)
- Configuration: Rename “Add New Option” → “Add option” [#843](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/843)
- Analysis details: Advanced options again in Details tab [#838](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/838)
- Analysis details: Rules tab with "Loading rules..." message waiting for table to be loaded
- Analysis list: more space between icons [#837](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/837)
- Initial page: wording on initial page (without projects) [#794](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/794)
> T794-837-838-843

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- ui/src/main/webapp/src/app/executions/active-executions-progressbar.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/shared/progress-bar.component.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Refer to task [#836](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/836)
- Completely remove the hint telling “Windup execution has started”.
- Rename “Active Executions” in “Active analysis”
- Add the analysis number of the current analysis. It should look as follows: `<Turning GIF> Analysis: #11937  Task: Executing ...`
- Replace the text “Cancel” with an icon 
- fixed tests
> T836 Active analysis page wording

- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.scss
- ui/src/main/webapp/src/app/executions/executions-list.component.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Changes for [#854](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/854)
- add "panel-body" div so that Analysis and Applications page have the titles aligned
- add "header-bar" to have the search box with scss file for related styles ("Run analysis" button added commented because it has to be added soon)
- filtering function works on id and status
- added span otherwise &nbsp; dis-aligned the trash icon in case of Cancelled analysis
> T854 Analysis list page: add basic filtering

- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/shared/status-icon.component.ts
Further enhancement requested by @Maarc:
"please use fa-times for the "cancel" action and replace the used fa-times icon for the "failed" symbol by "fa-ban" (like for CANCELLED)"
This PR completes #354
> T836 Icon enhancement for Cancel/Failed analysis

- pom.xml
- tsmodelsgen-invocation/pom.xml
- tsmodelsgen-maven-plugin/pom.xml
- tsmodelsgen-maven-plugin/src/it/sample-project/pom.xml
It seems PR #364 broke compilation.
~~~`RuleLoaderContext` is missing method `setFileBasedRulesOnly`.~~~
Update: 
It was caused by me having older version of windup-distribution. But meanwhile, @mareknovotny  updated artifact id to `4.0.0-SNAPSHOT` on windup and windup-distribution. So when I pulled latest version, it was already version 4 and because windup-web still depends on 3.1 I could not compile it.
I will remove it from my local cache and download latest 3.1.0 from maven central for now.
We can merge this PR whenever we decide to use version 4 in windup-web.
> Fix compilation

- services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java
- services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
- services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java
- services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java
- ui/src/main/webapp/src/app/core/events/windup-event.ts
- ui/src/main/webapp/src/app/project/migration-project.service.ts
- ui/src/main/webapp/src/app/services/windup-execution.service.ts
- ui/src/main/webapp/src/app/shared/abtract.service.ts
- ui/src/main/webapp/tests/app/services/windup-execution.service.spec.ts
…es crashes
This does a few things:
- Send a cancellation event for any related active executions just before deleting the project
- Mark the job as cancelled in the current server instance so that status updates no longer happen
- Treats status updates that come in for non-existent executions as a minor warning instead of a stacktrace
- Stops the client from monitoring related executions after a project is deleted
> Task 844: Deleting a project is not possible while an execution is in progress

- services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java
- services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java
Scenario:
1. Create a new project with 2 applications and run an analysis
2. Wait for the analysis to finish
3. Delete one of the applications
4. Run analysis with "Run Analysis" button on Analysis list page
Analysis fails with this exception [1]
I fix it filtering the used applications by checking if they're deleted.
Other possible ways could be:
- add a method "getAvailableApplications" to AnalysisContext that only returns the "not-deleted" applications
- force the user to go to the configuration page and push the "Save and Run" button because in this way the analysis works
[1]<details>SEVERE [org.jboss.windup.web.services.messaging.ExecutorMDB] (Thread-26 (ActiveMQ-client-global-threads-899373876)) Failed to execute windup due to: java.lang.IllegalArgumentException: Application does …
> T885 fix analysis fail after application deletion

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
Now in "Details" tab of analysis details page, if the analysis had the flag to also run the cloud readiness analysis, you'll see:
`Transformation path:    Migration to Red Hat JBoss EAP 7 (with cloud readiness analysis) `
> T908 Added cloud readiness analysis information to analysis details page

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.ts
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.scss
- ui/src/main/webapp/src/app/executions/executions-list.component.ts
- ui/src/main/webapp/tests/app/components/executions/executions-data.ts
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
- Analysis list page:
- created `getNumberAnalyzedApplications`, a dedicated method to calculate the number of analyzed applications
- add column w/ the number of analyzed applications
- Analysis details page:
- created `getAnalyzedApplications` to retrieve the analyzed applications because when an analysis is running the number of applications is 0
- rewording "Duration:" label in "Last Modification:" for running analysis
- Tests:
- created `analysisContext` data object for testing new column in analysis list page
- updated test that first was not working
@klinki still needs to be fixed the sorting in the 'Analyzed Applications' column because it's based not on an available field but on the value calculated from `getNumberAnalyzedApplications` method
BTW, maybe …
> T889 Add number of analyzed applications to the analysis list

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html
- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
If someone removes all the options from an advanced panel (i.e. deselect all the excluded packages) the panel automatically closes: this was not a requirement but it seems to be a good approach.
> T834 Configuration Page: Advanced Panels should automatically open if used

- ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.ts
- ui/src/main/webapp/src/app/configuration/technology.component.ts
- ui/src/main/webapp/src/app/executions/execution-detail.component.ts
- ui/src/main/webapp/src/app/reports/filter/report-filter-indicator.component.ts
- ui/src/main/webapp/src/app/reports/filter/report-filter.component.ts
Remove unnecessary `|any` workaround - windup-services is now .ts file
and not .d.ts module so this workaround is not needed anymore.
> Fix forgotten 'windup-services' module path

- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.scss
I also removed the `border-top` because after digging into CSS details, it turn out that the first entry in the left bar, if active, generates a strange "double" black line on hover event (see next screenshot).
Without the `border-top` entry, it's better (see next screenshot).
> T929 Left nav bar: replace white line - T930 Left nav bar: remove bold black line

- services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java
Previously, if the project were being updated, the default context would get destroyed.
With this change, we insure that we preserve it, even if the client does not send the data
(as it typically would not).
> Task 912: Fix Update Project

- ui/src/main/webapp/css/windup-web.css
- ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.html
- ui/src/main/webapp/src/app/configuration/configuration.component.html
- ui/src/main/webapp/src/app/configuration/configuration.component.ts
Added `button.btn` class to `windup.css` to have all the buttons `capitalize`d
Rows 31-35
|Existing Text	|Suggested Text	|Notes|
|---------- | ---------- | ---------- |
|Show rules	|Show Rules	|Buttons are title case  - consistency|
|Rules Path (file or directory)	|Rules path (file or directory)	|Field labels are sentence case - consistency|
|Path to the file or folder containing the rule(s).	|Path to the file or directory containing the rules.	|* It is unnecessary to do "(s)". It is fine in field labels to assume there are multiple, even if there will only be one.<br/>* Use "directory" to be consistent with (file or directory)|
|No rule found.	|No rules found.	||
"Confirm rule removal<br/>Do you really want to remove the rules from '/home/ahoffer/.windup/'?"|	"Confirm Rule …
> T935 Rules Configuration page: change texts

- ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.ts
Remove also 'openshift' target as well because these two targets are both selected with the "Cloud readiness analysis" check-box.
> T961 Advanced options: remove “cloud-readiness” from target's values

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
I inserted a "n/a" as `Last modification`'s value instead of removing `Last modification` field to keep the page's layout fixed (avoiding `Configuration` box to move down when `Last modification` is available).
> T969 Analysis details: fix visual layout of queued analysis

- ui/src/main/webapp/src/app/project/migration-project-form.component.html
- ui/src/main/webapp/src/app/project/migration-project-form.component.ts
`Create Project`, the first step of new project wizard, now has the focus on project's name input field just after the page has loaded.
More when, from project's name input field, you press `TAB` key you move to next text area for writing project's description in order to get quicker into filling values like the task requests.
> T972 Create Project step: focus on name input

- services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java
- ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.ts
Due to removing `openshift` as target id, it's not necessary to filter it anymore (see windup/windup-rulesets#204)
Even further, once we add it again as target in the future we'll be able to select it from values in advanced options.
> T978 Advanced options: no more filtering 'openshift' target

- ui/src/main/webapp/src/app/executions/active-executions-progressbar.component.html
- ui/src/main/webapp/src/app/shared/progress-bar.component.ts
- i put everyone as reviewer in order to discuss all together
- all styles added are in-line because it's a PR to discuss since there's no mockup about the goal to achieve; once the solution will be identified, i'll put every style in CSS file 
- all information is presented in just one line behind the heading in order to avoid having a lot of empty space when there's no active analysis.
- `There is no Active Analysis` style is headline
- `Click Run Analysis button to start a new analysis.` used to fill the line when there's no active analysis
- `Analysis: #{id}` i tried to keep enough space on the right to not have the bar too near
- `Task` information centered (i change the default behavior that makes it moving with the progress bar) in the progress bar because it's value changes and so …
> T968 Analysis list: fix the active analysis progress bars to not change page too dramatically

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html
- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.scss
- ui/src/main/webapp/src/app/shared/js-tree-angular-wrapper.component.ts
The box is height 240px to let the user see 10 values before scroll appears because each checkbox is height 24px.
10 entries seem to me a reasonable compromise between let the user see packages and not "destroy" page layout while navigating through packages.
It also been tested in wizard configuration step.
> T967 {In,Ex}cluded package checkboxes list into scrollable container

- services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java
- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
Taiga task #987.
- Do not automatically select all applications anymore in `AnalysisContextForm`
- Add newly uploaded applications to default `AnalysisContext`
> 987 - do not autoselect all applications

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
Save button doesn't navigate away anymore. It also doesn't create any  notification, so UI appears to be frozen/doing nothing. But it is requested :(
> 996 - Remove redirect from analysis context form

- ui/src/main/webapp/src/app/shared/dialog/confirmation-modal.component.html
- ui/src/main/webapp/src/app/shared/is-route-active.directive.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
First issue was caused by using [routerLink] property on
`wu-is-route-active`  directive. This property conflicts with Angular's one, so it needs
to be renamed.
Second issue was caused by not getting any output from user - dialog
was closed outside Angular's scope. To prevent that, use dialog which
cannot be closed by keyboard/clicking outside.
Solves https://issues.jboss.org/browse/WINDUP-1390
> Fix confirm leave modal dialog.

- ui/src/main/webapp/src/app/shared/progress-bar.component.ts
Now the text inside the progress bar does not go over the limit of the progress bar anymore but to achieve this i had to put it left-aligned just like the way it was before #430
> T1023 Active analysis: fix progress bar text

- ui/src/main/webapp/css/windup-web.css
This is the final result of the change:
> WINDUP-1425 Fix responsiveness when page is narrow

- pom.xml
- services/pom.xml
https://issues.jboss.org/browse/WINDUP-1433
> WINDUP-1433

- ui/src/main/webapp/src/app/registered-application/application-queue-list.component.html
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.html
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.scss
* weird spacing between uploaded and to-be-uploaded file lines has been fixed letting also the last element of the file list to have the negative padding 
* percentage value for uploading files has been placed right after the file size to not overlap anymore (giving some margin-right to `file-size` span)
* `100%` percentage value for uploaded files has been placed just after the file name to be consistent with the percentage positioning for uploading files: in this way we also avoid that the previously centered `100%` percentage label would have overlapped in case of narrow screen and long file name
* `.progress-bar` text color has been modfied to be color `#363636` to gain a better readablity  and to be consisten with color of other texts in the UI (white text is used for hover on …
> WINDUP-1441 File upload: lines spacing and upload percentage

- ui/src/main/webapp/src/app/registered-application/application-queue-list.component.html
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.html
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.scss
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.ts
- allows user to delete app from upload queue even if it is not currently uploading
- always show status icon next to progress bar
Status icon might be:
- cancel upload (remove from upload queue)
- upload cancelled (item in already cancelled state)
- delete application
#close WINDUP-1451
> Allow user to delete app from upload queue

- ui/src/main/webapp/css/windup-web.css
- ui/src/main/webapp/src/app/executions/project-executions.component.html
- ui/src/main/webapp/src/app/project/project-layout.component.ts
- ui/src/main/webapp/src/app/shared/navigation/navigation-responsive-styles.scss
https://issues.jboss.org/browse/WINDUP-1457
I discovered that `text-overflow: ellipsis `style is not working in every situation and it depends on size of browser window.
It seems that **width** css property is not properly set or inherited `max-width: none;` breaks the correct rendering
> WINDUP-1457: syncing context menu items with page titles

- ui/src/main/webapp/src/app/configuration/configuration.component.ts
- ui/src/main/webapp/src/app/configuration/technology-filter.ts
- ui/src/main/webapp/src/app/shared/chosen/chosen-abstract.ts
- ui/src/main/webapp/src/app/shared/chosen/chosen-multiple.component.ts
- ui/src/main/webapp/src/app/shared/chosen/chosen-single.component.ts
- ui/src/main/webapp/src/app/shared/filter/active-filters-list.component.html
- ui/src/main/webapp/src/app/shared/filter/active-filters-list.component.ts
- ui/src/main/webapp/src/app/shared/filter/dropdown-filter.component.html
- ui/src/main/webapp/src/app/shared/filter/dropdown-filter.component.ts
- ui/src/main/webapp/src/app/shared/filter/text-filter.component.ts
- ui/src/main/webapp/src/app/shared/shared.module.ts
- ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.html
- ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.ts
- ui/src/main/webapp/src/app/shared/utils.ts
Rules filtering enhanced to support versions. (Depends on #448 )
There are several issues, which needs to be resolved first:
1) we have 2 formats of technology entity: 
for example `hibernate` with versionRange: `[5,)`  and `hibernate5` 
I'm trying to enable selecting technology even without specifying version, so ideally I would like to have options: 
- `hibernate`
- `hibernate 5`
but now I will have:
- `hibernate`
- `hibernate 5`
- `hibernate5`
where `hibernate5` and `hibernate 5` are sort of duplicities. Also the they might not be interchangeable which would lead to confusion. 
2) Input now allows only to select from predefined options (which is probably not a real problem)
3) Version based filtering is not completely finished yet. It decomposes versionRange string into array following …
> Rules filtering part 2 - with version support

- ui/src/main/webapp/css/windup-web.css
- margin top to avoid notifications to be too near to top navigation bar
- margin bottom is good to not have a lot of empty space between notification itself and below div title
> Notifications formatting

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
The requirement was: 
"_clicking on the ID to get to the reports, and move getting information about the analysis execution to the actions column_"
Analysis list page:
- analysis id has the external link icon and links to the static report if the analysis is `COMPLETED`
- in the `Actions` column, for reaching the analysis details, the bar-chart icon has been changes with the info icon because the action is "getting information"
- tests have been updated
Analysis details page:
- added the link to the static report  if the analysis is `COMPLETED`
> WINDUP-1417 Analysis list and details page: get to Reports easily

- ui/src/main/webapp/src/app/configuration/configuration.component.html
- ui/src/main/webapp/src/app/configuration/configuration.component.scss
- ui/src/main/webapp/src/app/configuration/configuration.component.ts
- ui/src/main/webapp/src/app/configuration/rules-modal.component.html
* disabled `Show Rules` button (w/o deleting the modal component)
* added [PF Expanding Rows](https://www.patternfly.org/pattern-library/content-views/list-view/#/list-view-with-expanding-rows) to the existing list
* added all the rules in the expanded panel for each rule set
* added select box to scroll to a particular rule within the rule set
* added border all around the rule set header and its expanded panel to improve the visual feedback
* increased border between rule sets to avoid overlapping borders
* added to each rule text area a link to scroll up again to the rule set header
* at the beginning there was a requirement for having "scroll-bar inside the popup" so the change has been done even if now the modal window is not used anymore
> WINDUP-1501 Redesign rules configuration page

- ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
- ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts
Fix a NgZone issue after #454 introduces [`zone.runOutsideAngular`](https://github.com/windup/windup-web/pull/454/files#diff-e40e9ff89e95fe20d6426ddb4f89dadeR11) for handling remote calls to get the packages list for every application.
> WINDUP-1584 Fix package discovering (never ending)

- services/pom.xml
- services/src/main/java/org/jboss/windup/web/services/KeycloakAuthenticator.java
- services/src/main/java/org/jboss/windup/web/services/websocket/ExecutionProgressReporter.java
Retrieve the hostname from the socket itself. This method depends on undertow.
I tried this method first: https://webcache.googleusercontent.com/search?q=cache:uqS3eGVAcnoJ:https://java.net/jira/browse/WEBSOCKET_SPEC-235+&cd=1&hl=en&ct=clnk&gl=us
The method from java.net didn't work, though, as the thread can vary between the modifyHandshake call and the open call.
> WINDUP-1586: On master, Active analysis bar is not working

- services/src/main/java/org/jboss/windup/web/services/rest/UnhandledExceptionHandler.java
- services/src/test/java/org/jboss/windup/web/services/rest/UnhandledExceptionHandlerTest.java
- ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.ts
- ui/src/main/webapp/src/app/configuration/rule.service.ts
- ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
- ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.ts
- ui/src/main/webapp/src/app/shared/utils.ts
- improved parsing of server response - now it won't fail when response is not valid JSON
- improved exception handling on backend:
- catch all exceptions in `UnhandledExceptionHandler`, not only `RuntimeException` (this should reduce number of situations when server responds with plaintext/html message instead of JSON) 
- all exceptions are not considered `"Database constraints were not met."` anymore. (This was caused by bug in `findFirstOccurenceInExceptionChain` methods.
> Improve exception handling

- ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.ts
Problem was with `ExecutionApplicationListComponent` making requests after route-change event received on `this.flatRouteLoaded.subscribe` Observable. 
When leaving this component, route events should not be received anymore. Cause was empty `ngOnDestroy` method which shadowed inherited one.
> WINDUP-1598 - Fix execution id NaN exceptions.

- ui/src/main/webapp/src/app/configuration/configuration.component.html
- ui/src/main/webapp/src/app/configuration/configuration.component.scss
- ui/src/main/webapp/src/app/configuration/configuration.component.ts
In rules configuration form, show only migration rules.
#close WINDUP-1382
> WINDUP-1382 - Show only MigrationRulesPhase rules

- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/EJBResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/EJBResourceImpl.java
- services/src/main/java/org/jboss/windup/web/services/rest/RestApplicationFurnace.java
- ui/src/main/webapp/src/app/executions/executions-layout.component.ts
- ui/src/main/webapp/src/app/project/project-layout.component.ts
- ui/src/main/webapp/src/app/reports/application-level-layout.component.ts
- ui/src/main/webapp/src/app/reports/reports-routing.module.ts
- ui/src/main/webapp/src/app/reports/reports.module.ts
- ui/src/main/webapp/src/app/reports/source/source-report.component.html
- ui/src/main/webapp/src/app/reports/technologies/tech-report.service.ts
- ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.html
- ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.scss
- ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.ts
- ui/src/main/webapp/src/app/services/graph.service.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu-link.component.ts
- ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
**Changes**
* enable `Tecnologies` entry in left nav bar both at analysis and application level
* add 2nd level menu on left nav bar (`isEnable` field is working for showing/hiding entries)
* add `EJB report` (with [other table layouts commented](https://github.com/windup/windup-web/compare/master...mrizzi:JIRA_WINDUP-1578?expand=1#diff-ef17ccf18496515ea6cd211fe828e92fR43)) with new dedicated methods in `tech-report.service.ts` to retrieve data from graph
* add in `graph.service.ts` the property name and value handling to call the `/{executionID}/by-type/{vertexType}/{propertyName}={propertyValue}` service to retrieve separately `Stateless` and `Stateful` EJBs
* change `Source code` page to have the standard layout for header and spacing from nav bars
**To fix**
Error: Cannot find primary …
> WINDUP-1578 Dynamic EJB Report and 2nd level menu

- pom.xml
- tests/e2e/pom.xml
- tsmodelsgen-invocation/pom.xml
https://issues.jboss.org/browse/WINDUP-1558
some conflicts between xml-maven-plugin and wildfly-maven-plugin in e2e tests - so commented the html report generation for now
> WINDUP-1558: adding findbugs profile to check staticaly java source code

- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.ts
Now, in the analysis details page, when the analysis is queued, for consistency with analysis list page, there's no more the progress bar but a label indicating how long the analysis is queued.
> WINDUP-1661: Analysis details disabled progress bar when analysis is queued

- ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.html
- ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.ts
- ui/src/main/webapp/src/app/reports/technologies/hibernate/hibernate-report.component.html
- ui/src/main/webapp/src/app/reports/technologies/remote-services/remote-services-report.component.html
- ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.html
- ui/src/main/webapp/src/app/shared/all-data-filtered-message.component.html
- ui/src/main/webapp/src/app/shared/all-data-filtered-message.component.ts
- ui/src/main/webapp/src/app/shared/shared.module.ts
- ui/src/main/webapp/src/app/shared/table/table-panel.component.html
- ui/src/main/webapp/src/app/shared/table/table-panel.component.ts
- ui/src/main/webapp/src/app/shared/table/table.component.html
- ui/src/main/webapp/src/app/shared/table/table.component.ts
I have noticed some more issues with filtering here, so this is more comprehensive solution. 
I renamed `wu-table` to `wu-table-panel` (since it has panel, panel header and also empty message and more things then just a `<table>`)
and simplified `wu-table` to truly represent only `<table>` and nothing else. This makes it more reusable, so it could be used in application list.
> WINDUP-1772 - dynamic reports app list sorting

- addons/pom.xml
- addons/web-support/addon/pom.xml
- addons/web-support/api/pom.xml
- addons/web-support/impl/pom.xml
- addons/web-support/pom.xml
- addons/web-support/tests/pom.xml
- ear/pom.xml
- furnace-service-provider/pom.xml
- pom.xml
- services/pom.xml
- tests/pom.xml
- tests/test-authentication-client/pom.xml
- tests/wildfly-dist/pom.xml
- tsmodelsgen-invocation/pom.xml
- tsmodelsgen-maven-plugin/pom.xml
- ui/pom.xml
changed artifact version from `4.1.0-SNAPSHOT` to `4.0.1-SNAPSHOT` and consistently also `<version.windup>` tag.
done using `mvn --batch-mode release:update-versions -DdevelopmentVersion=4.0.1-SNAPSHOT` command from the [maven-release-plugin](http://maven.apache.org/maven-release/maven-release-plugin/examples/update-versions.html#)
> prepare for next release

- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphCache.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphCacheImpl.java
- addons/web-support/impl/src/test/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphCacheTest.java
- services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java
Steps to reproduce the bug on master:
- Run an analysis
- Delete the analysis
- Observe the server log - within a minute or two exceptions should start to repeatedly appear
If this doesn't work, then view a dynamic report between steps 1 and 2.
> Fix for issue with exceptions after deleting a closed graph

- addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/MessagingProgressMonitor.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java
- model/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java
When rule provider fails to load a rule, the message is displayed in the execution log tab in the analysis details.
> WINDUP-1676 Log to web ui when rule providers fails to load a rule

- ui/src/main/webapp/src/app/services/windup-execution.service.ts
Now the pattern `http` is replaced only if at the beginning of the URL (and no matter if then followed by the "secure" `s` or not)
> WINDUP-1975 Analysis progress bar sometimes fails to update

- ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html
Now you can browse to `Rules Configuration` from `Analysis Configuration` wizard and then go successfully back to `Analysis Configuration`
> WINDUP-1973 Fix Rules Configuration link in Analysis Configuration

- ui/src/main/webapp/src/app/app-routing.module.ts
- ui/src/main/webapp/src/app/app.module.ts
- ui/src/main/webapp/src/app/core/core.module.ts
https://issues.jboss.org/browse/WINDUP-1670
This just redirects back to the project-list if there is no route available for the url. This should really only happen if the user manually puts in a url.
> WINDUP-1670: Handle non-existent routes

- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/AbstractGraphResource.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResourceImpl.java
- services/src/test/java/org/jboss/windup/web/services/rest/graph/GraphResourceTest.java
- ui/src/main/webapp/src/app/executions/executions-list.component.html
- ui/src/main/webapp/src/app/executions/rule-provider-executions/rule-provider-executions.service.ts
The issue is fixed by [this single change](https://github.com/windup/windup-web/compare/master...mrizzi:WINDUP-1984?expand=1#diff-4940c966aeb3a065b8a4be389fddb007R181) to set the right edge traversal order.
As requested in the issue [WINDUP-1984](https://issues.jboss.org/browse/WINDUP-1984), all the other changes address a better performance for the service:
- taking away `vertices_in` and `ruleContents` (together with other unused fields) has slimmed the response for about 760 rules executed from ~1MB to ~200KB
- [return Response](https://github.com/windup/windup-web/compare/master...mrizzi:WINDUP-1984?expand=1#diff-6099b4355e63519c046530a5ebb619fcR91) has improved the marshalling of the response with a gain of other ~2 seconds
So from the ~7 seconds for the 4.0.1.Final release, now it …
> WINDUP-1984 Execution Details - Rules tab fix

- build/release_windup_web.sh
https://issues.jboss.org/browse/WINDUP-2105
There's no need to build and release `windup-keycloak-tool` project anymore.
> WINDUP-2105 Release separately windup-keycloak-tool

- addons/messaging-executor/addon/pom.xml
- addons/messaging-executor/api/pom.xml
- addons/messaging-executor/impl/pom.xml
Need to fix some versions to `${project.version}` value after they became wrong in this commit https://github.com/windup/windup-web/commit/3736afa56131de8fbd8874e64805ab783b93b213#diff-57f9528e5593bfeefff2c70e004f39d5
> WINDUP-2059 fixing some versions after Alpha releases

- pom.xml
It works with:
* Apache Maven 3.5.2 (Red Hat 3.5.2-5)
* Java version: 1.8.0_172
Related to https://github.com/windup/windup-web-distribution/pull/52 and due to https://issues.jboss.org/browse/WFMP-94
> WINDUP-2113 Upgrade wildfly-maven-plugin to 1.2.2.Final

- addons/messaging-executor/addon/pom.xml
- addons/messaging-executor/api/pom.xml
- addons/messaging-executor/impl/pom.xml
After https://github.com/windup/windup/pull/1328 has been merged, the `<version>${project.version}</version>` for `windup-server-provider-spi` can be removed, allowing the execution of automated releases
> WINDUP-2101 Removing version for windup-server-provider-spi artifact

- addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/AbstractSerializer.java
- addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/HttpPostSerializer.java
- addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtil.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtilImpl.java
- addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java
- model/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java
- model/src/main/java/org/jboss/windup/web/services/model/Package.java
- model/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java
- services/src/test/java/org/jboss/windup/web/services/data/WindupExecutionUtil.java
- ui/src/main/webapp/src/app/executions/execution-detail.component.html
- ui/src/main/webapp/src/app/executions/execution-detail.component.ts
- ui/src/main/webapp/src/app/services/graph.service.ts
- ui/src/main/webapp/src/app/services/windup-execution.service.ts
Depends on https://github.com/windup/windup/pull/1342
- exclusion of the `archives` folder from the tar archive sent from the executor to the web console at the end of an analysis when RHAMT is executed on OpenShift
- added information in the log about the quantity of data sent
- added the ability to persist the graph outside of the standard analysis output folder (useful in an OCP installation with an NFS shared storage where BerkeleyDB can not persist data)
> WINDUP-2258 Enhancements to work with NFS shared storage

- README.md
I had some problems following the instructions of the README file so I thought it would be good to add some information to the README file:
- I added the command for Fedora OS, to install npm `sudo dnf install npm`
- I changed `<deployment name="rhamt-web/api" runtime-name="rhamt-web/api.war">` to `<deployment name="rhamt-web/api" runtime-name="api.war">` in order to allow readers just to copy and paste the instructions of the README file. Otherwise is allways necessary to change it manually.
- I added a block of text called **Watch your changes while coding** at the end of the README file. The text contains information about how to start webpack in order to watch changes while coding. It also contains the specific version of webpack that developeres must use **(webpack@3.4.1)**. …
> WINDUP-README docs

- ui/src/main/webapp/src/app/project/project-list.component.html
- ui/src/main/webapp/src/app/project/project-list.component.scss
This is another approach of letting the user see the name and description of a project.
1. This PR creates a new action button on the project list page; this action button will show the entire name and description of the project.
> WINDUP-2308 Project List - Project Name Truncated V2

- README.md
- services/pom.xml
The `swagger` profile can be used to create the OpenAPI/Swagger specifications file both at compile time and at runtime.
> Swagger: compile and runtime files generation, README update

- services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationOptionsEndpointImpl.java
https://issues.redhat.com/browse/WINDUP-2490
Removed the `UserLabelsDirectoryOption` option from the advanced options
> WINDUP-2490: userLabelsPath appearing in Advanced options

- pom.xml
- services/pom.xml
- tsmodelsgen-invocation/pom.xml
- tsmodelsgen-maven-plugin/pom.xml
- ui/src/main/webapp/package.json
https://issues.redhat.com/browse/WINDUP-2505
Modified versions of :
* Keycloak   -> from 4.8.3   to  8.0.1
* Wildfly       -> from 15.0.1.Final to 18.0.1.Final
* Hibernate  -> from 5.3.7 to 5.3.14
> Windup 2505 migrate windup web libraries

- tools/graph-tool/src/main/webapp/messages.xlf
- ui/src/main/webapp/messages.xlf
https://issues.redhat.com/browse/WINDUP-2566
Change the files `**/messages.xlf`
Note: the files `messages.xlf` are used for localization and translation using Angular Tools. Windup-web don't really use this at the moment. For more info about `messages.xlf` we can take a look to:
- https://angular.io/guide/i18n
- https://www.youtube.com/watch?v=3QR8p03eKAk
> WINDUP-2566: RHAMT Rebranding - windup-web

- ui/src/main/webapp/src/app/shared/add-labels-path-modal/add-labels-path-modal.component.ts
- ui/src/main/webapp/src/app/shared/add-rules-path-modal/add-rules-path-modal.component.ts
https://issues.redhat.com/browse/WINDUP-2675
The "Add Rule/Label Modal" should only accept valid files. Valid files are verified only based on its name.
- Valid rule files: "*.windup.xml", "*.rhamt.xml", "*.mta.xml"
- Valid label files: "*.windup.label.xml", "*.rhamt.label.xml", "*.mta.label.xml"
> WINDUP-2675: RFE :Web-Console UI : any xml file can be uploaded in rules like pom.xml or label.xml

- ui-pf4/src/main/webapp/src/components/project-details-form/schema.ts
https://issues.redhat.com/browse/WINDUP-2830
Using exactly the same regex used in Hibernate https://github.com/windup/windup-web/blob/60ee612fbfc4c6dd1d1a8492d3f08dc298f721cb/model/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java#L70
> WINDUP-2830: Validation error if the first letter of project name is a number

- ui-pf4/src/main/webapp/src/components/project-context-selector/project-context-selector.tsx
- ui-pf4/src/main/webapp/src/containers/projectcontext-pagesection-container/projectcontext-pagesection-container.tsx
https://issues.redhat.com/browse/WINDUP-2820
Project context selector: search while typing.
> WINDUP-2820: Search project should search as we start typing the text

- ui-pf4/src/main/webapp/src/components/upload-files-dropzone/upload-files-dropzone.tsx
https://issues.redhat.com/browse/WINDUP-2821
Add error message when uploading files. The message comes directly from the Backend.
> WINDUP-2821: Show errow messages when trying to upload file types not supported

- ui-pf4/src/main/webapp/src/pages/projects/new-project/review/review.tsx
https://issues.redhat.com/browse/WINDUP-2854
Added nullable function to replace possible empty React nodes with `none`.
> WINDUP-2854: New PF4 UI : Add "source" field to the review page and "none" if field is empty

- ui-pf4/src/main/webapp/src/layout/ButtonAboutApp/ButtonAboutApp.scss
- ui-pf4/src/main/webapp/src/layout/ButtonAboutApp/ButtonAboutApp.tsx
- ui-pf4/src/main/webapp/src/layout/ButtonAboutApp/__tests__/__snapshots__/ButtonAboutApp.test.tsx.snap
https://issues.redhat.com/browse/WINDUP-2824
Replaced <dt/> by <grid> to allow MTA version labels to be splitted in when md, sm, xs
> WINDUP-2824: About page: change git revision labels' style

- ui-pf4/src/main/webapp/src/components/project-details-form/schema.ts
- ui-pf4/src/main/webapp/src/components/project-details-form/tests/project-details-form.test.tsx
https://issues.redhat.com/browse/WINDUP-2843
Changed the error message for "Project name" and also changed the regex which validates it since the previous was catching special characters as valid characters.
> WINDUP-2843: Improve warning message for project name

- ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx
https://issues.redhat.com/browse/WINDUP-2850
Added a spinner to the alert and also a link to redirect the user to the "Analysis results" page.
> WINDUP-2850: MTA Web UI - PF4 - Enhance the alert in "Applications" to give a sense of "analysis in progress"

- ui/src/main/webapp/css/windup-web.css
https://issues.redhat.com/browse/WINDUP-2857
Fix css for correct spaces between content and navbar. The bugs were originated when the "green" bar with the link for the new UI was introduced.
> WINDUP-2857: Fix PF3 UI : space beetween navbar and main content is too small

- ui-pf4/src/main/webapp/src/containers/delete-dialog/delete-dialog.tsx
- ui-pf4/src/main/webapp/src/pages/analysis-results/execution-details/execution-details.tsx
- ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
- ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx
https://issues.redhat.com/browse/WINDUP-2862
https://issues.redhat.com/browse/WINDUP-2863
https://issues.redhat.com/browse/WINDUP-2864
WINDUP-2862 Change delete confirmation dialog text
WINDUP-2863 Remove `#` in application deletion
WINDUP-2864 Adding `analysis` in analysis deletion
> WINDUP-2862/3/4 Delete confirmation dialog box fixes

- ui-pf4/src/main/webapp/src/components/advanced-options-form/advanced-options-form.tsx
https://issues.redhat.com/browse/WINDUP-2870
Increased space between columns:
BEFORE:
AFTER:
> WINDUP-2870: PF4 Web UI - advanced options space between form columns

- ui-pf4/src/main/webapp/cypress/integration/new-project.spec.js
- ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
- ui-pf4/src/main/webapp/src/components/transformation-path/transformation-path.tsx
- ui-pf4/src/main/webapp/src/pages/projects/new-project/wizard/project-wizard.tsx
https://issues.redhat.com/browse/WINDUP-2869
- Changed `transformation path` by `transformation target`
- Changed `Red Hat Runtimes` by `Spring Boot on Red Hat Runtimes`
> WINDUP-2869: PF4 Web UI - Red Hat Runtimes - change transformation path

- ui-pf4/src/main/webapp/src/Constants.tsx
- ui-pf4/src/main/webapp/src/components/advanced-options-form/advanced-options-form.tsx
- ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts
https://issues.redhat.com/browse/WINDUP-2873
- Removed "Included tags" from the advanced options.
- The "Excluded tags" won't be removed since it does not generate any bug, only "Include tags" does.
> WINDUP-2873: MTA Web UI - PF4 - Hide include Tags Advanced Option

- ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx
https://issues.redhat.com/browse/WINDUP-2877
This PR fixes the way to check "Active analysis" from a Project.
The way of detecting the number of active analysis is based on 2 data sources:
- The list of executions coming from the endpoint `/mta-web/api/windup/by-project/{projectId}` which returns a static list of executions from a project.
- The list of executing coming from the websocket.
The first data source has more priority over the second; the second source of data will be used only for the "active" elements of the first data source, in short words: "Only check the Websocket if the analysis is running or waiting in a queue"
> WINDUP-2877: MTA Web UI - PF4 - Applications page - info alert doesn't disappear

- ui-pf4/src/main/webapp/src/Constants.tsx
- ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts
https://issues.redhat.com/browse/WINDUP-2829
- Changed label "Tattletale" by "Disable Tattletale"
- Changed the default tooltip of "Disable Tattletale"
- Changed the CLI property used for "Disabled Tattletale"
> WINDUP-2829: MTA 5.1.0 alpha build : Tattletale report links are broken

- ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts
https://issues.redhat.com/browse/WINDUP-2878
https://issues.redhat.com/browse/WINDUP-2880
This PR contains 3 changes in the "Advanced options" page:
- Change "spring" to "springboot" in the tooltip of the field "**Source**".
- Set a description, which ends with a period, to the field "**Additional classpath**"
- Set a description to the switch "**Source mode**"
> WINDUP-2878, WINDUP-2880: Advanced Options tooltips change

- ui-pf4/src/main/webapp/src/components/package-dual-list/package-dual-list.tsx
https://issues.redhat.com/browse/WINDUP-2881
Changes:
- Removed virtualization of the tree (virtualization enhances the performance in the case of thousands of nodes in the tree). Even though virtualization is a good feature, it makes the scroll to disappear unless the user moves the scroll and makes the UX poor so I think it is good to remove it.
- Set a static heigh size to the tree.
To test this PR use the application linked in this [JIRA comment](https://issues.redhat.com/browse/WINDUP-2881?focusedCommentId=15512746&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15512746)
> Remove virtualizacion of tree and set height

- ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx
https://issues.redhat.com/browse/WINDUP-2899
If the application is "exploded" then the link for downloading the file will disappear and just the title of the file will appear
> WINDUP-2899: Link to download "server path" application is not working

- ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
https://issues.redhat.com/browse/WINDUP-2901
This PR adds an additional field to the "card model" which is `default` to point which dropdown is selected by default when the card is not selected. Also adds a temporary `default` field to keep the changes made by the user.
If you deselect the EAP transformation target,  then select it again, it defaults to eap6, rather than eap7
> WINDUP-2901: EAP target pre-selected value

- ui-pf4/src/main/webapp/src/components/add-applications-form/add-applications-uploadfiles-form.tsx
https://issues.redhat.com/browse/WINDUP-2913
If an application fails to be uploaded then the user is now able to delete that row.
> WINDUP-2913: Allow user to delete an application if app upload failed

- .github/workflows/ci-actions.yml
This PR contains an extract from https://github.com/windup/windup-web/pull/666 and will only execute unit tests for the PF4 UI. 
Unlike https://github.com/windup/windup-web/pull/666, this PR is stable since it does not build entire web distribution and only relies on the NPM registry availability (for downloading the npm packages)
> Github Actions: Add unit tests executions for the PF4 UI

- ui-pf4/src/main/webapp/src/components/rule-label-title/rule-label-title.tsx
- ui-pf4/src/main/webapp/src/components/rule-label-title/tests/rule-label-title.test.tsx
- ui-pf4/src/main/webapp/src/containers/custom-labels/custom-labels.tsx
- ui-pf4/src/main/webapp/src/containers/custom-rules/custom-rules.tsx
- ui-pf4/src/main/webapp/src/pages/global-labels/user-provided/user-provided.tsx
- ui-pf4/src/main/webapp/src/pages/global-rules/user-provided/user-provided.tsx
https://issues.redhat.com/browse/WINDUP-2906
This PR makes a small change in order to show the words "label" or "rule" depending on which of those components we are located in. See the screenshots of the ticket.
> WINDUP-2906: [UI] Same tooltip for invalid labels and rules files

- services/src/main/webapp/WEB-INF/jboss-web.xml
- tools/graph-tool/src/main/java/org/jboss/windup/web/ui/FreemarkerServlet.java
- ui-pf4/src/main/java/org/jboss/windup/web/ui/PF4FreemarkerServlet.java
- ui-pf4/src/main/webapp/src/api/apiInit.ts
- ui/src/main/java/org/jboss/windup/web/ui/FreemarkerServlet.java
https://issues.redhat.com/projects/WINDUP/issues/WINDUP-2940
Static reports url changed from `/mta-web/api/static-report/2/index.html` to `/mta-ui/api/static-report/2/index.html`
> WINDUP-2940: Static reports available through new "mta-ui" context

- ui-pf4/src/main/webapp/src/pages/projects/new-project/review/review.tsx
https://issues.redhat.com/browse/WINDUP-2915
Change `target` by `targets`. See screenshot.
> WINDUP-2915: UI PF4- Wizard Review page enhancement

- services/pom.xml
- `argsx` was a typo
- `activeByDefault` is disabled when a profile is enabled so the property `debug` has been added to ensure it's enabled also when debugging
- no usage/value for `surefire.server.jvm.args` property has been found anywhere so it has been replaced with `jvm.debug.args`
> Restored 'debug' profile

- ui-pf4/src/main/webapp/src/pages/projects/new-project/review/review.tsx
https://issues.redhat.com/browse/WINDUP-3320
- Added SOURCES to the review page
- The set of Sources should no longer appear in the Advanced options, at the bottom of the review page.
> [WINDUP-3320] - Improvements to the presentation of the 'Review project details'

- furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/WebProperties.java
https://issues.redhat.com/browse/WINDUP-3333
> [WINDUP-3333] - Web Console fails to start if any of the parent folders contains blank spaces

- ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
- ui-pf4/src/main/webapp/src/components/select-card/select-card.tsx
- OpenJDK 17 is the default selected in the Dropdown of its CARD.
- Requires https://github.com/windup/windup-rulesets/pull/734
> Add openjdk17 to the transformation path page

- ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
See [JIRA ticket](https://issues.redhat.com/browse/WINDUP-3209).
> [WINDUP-3209] Enable EAP8 target

- model/src/main/java/org/jboss/windup/web/services/model/AdvancedOption.java
- model/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java
- model/src/main/java/org/jboss/windup/web/services/model/Configuration.java
- model/src/main/java/org/jboss/windup/web/services/model/LabelsPath.java
- model/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java
- model/src/main/java/org/jboss/windup/web/services/model/Package.java
- model/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java
- model/src/main/java/org/jboss/windup/web/services/model/ReportFilter.java
- model/src/main/java/org/jboss/windup/web/services/model/RulesPath.java
- model/src/main/java/org/jboss/windup/web/services/model/Tag.java
Changes needed for the upgrade to H2 V2 in https://github.com/windup/windup-web-distribution/pull/94
- boolean columns needed to be explicitly mapped to a type in db, hence using Hibernate `@Type`
- `AdvancedOption` Entity is using a reserved word `value` as a column name. Hence escaping it. Reserved words can be found at http://www.h2database.com/html/advanced.html
> H2 upgrade

- ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
Label is incorrectly named since the addition of support for EAP 8 migration path
> Fix to application server migration label

- ui-pf4/src/main/webapp/src/images/UI_Icon-Red_Hat-Search-A-Red-RGB.svg
- ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3558
depends on https://github.com/windup/windup-rulesets/pull/779
The new card has been added as the last one (ref. screenshot)
> Added 'Discovery' card to Transformation Paths page

- ui-pf4/src/main/webapp/src/components/package-dual-list/package-dual-list.tsx
- ui-pf4/src/main/webapp/src/components/package-selection/package-selection.tsx
- ui-pf4/src/main/webapp/src/pages/analysis-configuration/configuration-details/packages/packages.tsx
- ui-pf4/src/main/webapp/src/pages/projects/new-project/select-packages/select-packages.tsx
https://issues.redhat.com/browse/WINDUP-3513
- The packages selection has now a "Switch" component to allow the user to explicitly indicate that he wants to customize the set of packages to be analyzed. If the "Switch" is ON then the UI will analyze all packages the user selects; if the "Switch" is OFF then no packages will be selected, therefore Windup will analyze the app in the same the CLI does by default.
> [WINDUP-3513] - MTA Web UI - Known Libraries are being analyzed erroneously

- addons/messaging-executor/addon/pom.xml
backports #856 
depends on #859
> Bump sshd-common from 2.8.0 to 2.9.2

- .github/workflows/pr_build_jdk11.yaml
> Enabled jobs execution on 'releases' branches (#859)

- services/src/main/java/org/jboss/windup/web/services/rest/FileEndpoint.java
- services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpoint.java
- ui-pf4/src/main/webapp/src/api/api.tsx
https://issues.redhat.com/browse/WINDUP-3670
A previous PR upgraded the npm Axios dependency fixing an issue described here https://github.com/axios/axios/issues/4034 .
After debugging the app the issue ended up being a wrong use of the header "Content-Type" at the moment of verifying paths. The backend, master branch, currently `@consumes` "application-json" bodies; however, the UI sends plain text.
- The UI sends a path `"/home/myuser/folderA"`
- The backend receives the path in this way : `""/home/myuser/folderA""` (with additional quotes)
This PR changes the Content-Type header and use the correct ones.
> [WINDUP-3670] - Server path is checking if directory is empty

- ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
Add the Azure Spring Apps as Azure Target
I also update the ruleset as https://github.com/windup/windup-rulesets/pull/918
> Add Azure Spring Apps as the target for azure

- ui-pf4/src/main/webapp/src/containers/add-application-button/add-application-button.tsx
- ui-pf4/src/main/webapp/src/pages/projects/new-project/add-applications/add-applications.tsx
- ui-pf4/src/main/webapp/src/pages/projects/new-project/create-project/create-project.tsx
https://issues.redhat.com/browse/WINDUP-3845
Issue introduced at https://github.com/windup/windup-web/pull/865 when upgrading the library `formik`. An old version behaves differently than the last version.
- Have windup web console running locally
- Try to create a new project
- Use Chrome + use Chrome tools to make the network really slow (see image below)
- After filling the name of the project try to click on "Next"
Explanation to the issue: the form is being validated in both "When the form changes" and "on blur (when the input boxes lose the focus)". When the user fills the input boxes and tries to click on "Next" the "onBlur" validation is fired blocking the "Next" button and not allowing it to go to the next page.
> [WINDUP-3845] - Project details: Need to click twice the "Next" button to proceed to the next step

- ui-pf4/src/main/webapp/src/components/add-rulelabel-tabs/add-rulelabel-tabs.tsx
- ui-pf4/src/main/webapp/src/pages/projects/edit-project/edit-project.tsx
- ui-pf4/src/main/webapp/src/pages/projects/project-list/components/edit-project-modal.tsx
https://issues.redhat.com/browse/WINDUP-3877
Fix applied to 2 places:
- Edit project (project list => edit button)
- Add custom labels/rules using server path (create a project then once it is created go to "Analysis configuration", then "custom rules/labels", then click on "Add rule/label", then use "Server path")
To reproduce the error Use Chrome + use Chrome tools to make the network really slow (see image below). This way the issue clearly appears.
> [WINDUP-3877] - Edit Project : Need to click twice the "Save" button to edit a project

- ui-pf4/pom.xml
https://issues.redhat.com/browse/WINDUP-3892
The direct dependency injecting the htmlunit dependency is `org.jboss.arquillian.graphene:graphene-webdriver:2.5.4` and we are already using the latest stable version of it https://mvnrepository.com/artifact/org.jboss.arquillian.graphene/graphene-webdriver . Therefore, as we can no upgrade the direct dependency, we need to exclude the htmlunit dependency from `org.jboss.arquillian.graphene:graphene-webdriver:2.5.4` and inject it as a direct dependency
> [WINDUP-3892] - Upgrade htmlUnit dependency

- pom.xml
- services/pom.xml
https://issues.redhat.com/browse/WINDUP-3578
> WINDUP-3578: pom changes for CVE-2022-4492

- ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3943
> [WINDUP-3943] - JBoss Web Server 6 

- ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3972
> [WINDUP-3972] - Transformation targets - Web UI - OpenJDK21 plus other tweaks

- ui-pf4/src/main/webapp/src/components/transformation-path/transformation-path.tsx
Steps to reproduce the issue:
- Change this line https://github.com/windup/windup-web/blob/master/ui-pf4/src/main/webapp/src/layout/ThemeUtils.tsx#L81 and replace `"windup"` by `"mtr"` because the issue only happens with the MTR cards
- run the ui and in the in the "transformation path" page select and unselect "camel" dropdown values
Use Chrome to do the tests since the issue does not appear in Firefox
> fix: Add Padding to the cards to avoid MTR cards to change width while selecting camel

- model/src/main/java/org/jboss/windup/web/services/json/WindupExecutionJSONUtil.java
- pom.xml
upgrade jackson-databind for CVE
https://issues.redhat.com/browse/WINDUP-3926
> WINDUP-3926

- pom.xml
https://issues.redhat.com/browse/WINDUP-4123
This PR handles the CVE linked in the JIRA for the upstream windup build ( downstream is taken are of by the pipeline config)
> WINDUP-4123: upgrade keycloak to v24.0.3

- pom.xml
This will backport the following commits from `master` to `releases/6.3.z`:
- [WINDUP-4123: upgrade keycloak to v24.0.3 (#978)](https://github.com/windup/windup-web/pull/978)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [releases/6.3.z] WINDUP-4123: upgrade keycloak to v24.0.3 (#978)

- ui-pf4/src/main/webapp/package.json
- ui-pf4/src/main/webapp/src/store/alert/actions.tsx
- ui-pf4/src/main/webapp/src/utils/modelUtils.ts
- ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-4139
> WINDUP-4139:axios upgrade to 0.28.0

- ui-pf4/src/main/webapp/package.json
- ui-pf4/src/main/webapp/src/api/apiInit.ts
- ui-pf4/src/main/webapp/src/store/alert/actions.tsx
- ui-pf4/src/main/webapp/src/utils/modelUtils.ts
- ui-pf4/src/main/webapp/yarn.lock
This will backport the following commits from `master` to `releases/6.3.z`:
- [WINDUP-4139:axios upgrade to 0.28.0 (#975)](https://github.com/windup/windup-web/pull/975)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [releases/6.3.z] WINDUP-4139:axios upgrade to 0.28.0 (#975)
