addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/model/RegisteredApplicationModel.java
A query is issued every 1 second by the UI
11:13:37,878 WARNING [com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx] (default task-43) Query requires iterating over all vertices [(inputPath = /home/ondra/work/Migration/TestApps/_apps/jee-example-app-1.0.0-unparsable.ear)]. For better performance, use indexes
=> @Indexed inputPath

services/pom.xml, services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java, services/src/main/java/org/jboss/windup/web/services/model/MigrationPath.java, services/src/main/java/org/jboss/windup/web/services/model/Technology.java, services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationPathEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationPathEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/MigrationPathService.java, services/src/main/java/org/jboss/windup/web/services/service/TechnologyService.java, services/src/main/resources/migration-paths/migration-paths.xml, services/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, services/src/test/java/org/jboss/windup/web/services/AbstractTest.java, services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationPathEndpointTest.java, ui/src/main/webapp/app/components/analysiscontextform.component.html, ui/src/main/webapp/app/components/analysiscontextform.component.ts, ui/src/main/webapp/app/components/app.component.ts, ui/src/main/webapp/app/components/applicationgroupform.component.ts, ui/src/main/webapp/app/components/formcomponent.component.ts, ui/src/main/webapp/app/components/grouplist.component.html, ui/src/main/webapp/app/components/grouplist.component.ts, ui/src/main/webapp/app/components/migrationprojectform.component.ts, ui/src/main/webapp/app/components/registerapplicationform.component.ts, ui/src/main/webapp/app/services/analysiscontext.service.ts, ui/src/main/webapp/app/services/migrationpath.service.ts
=> Task 95 (analysis context edit/create)

.gitignore, README.md, scripts/eap-setup.cli, services/src/main/java/org/jboss/windup/web/services/WindupWebProgressMonitor.java, services/src/main/java/org/jboss/windup/web/services/messaging/AbstractMDB.java, services/src/main/java/org/jboss/windup/web/services/messaging/ExecutorMDB.java, services/src/main/java/org/jboss/windup/web/services/messaging/MessagingConstants.java, services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java, services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, services/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/validators/FileExistsValidator.java, services/src/test/java/org/jboss/windup/web/services/rest/RuleEndpointTest.java, services/src/test/resources/WEB-INF/activemq-jms.xml, services/src/test/resources/arquillian.xml, ui/src/main/webapp/app/components/grouplist.component.ts, ui/src/main/webapp/app/components/progressbar.component.ts, ui/src/main/webapp/app/components/projectlist.component.ts, ui/src/test/java/org/jboss/windup/web/ui/AbstractUITest.java, ui/src/test/resources/WEB-INF/activemq-jms.xml, ui/src/test/resources/arquillian.xml
This probably breaks tests, but feel free to look over the implementation. Known missing things:
- CLI scripts to make tests work again
- Instructions on how to setup your local environment (JMS setup now required)
I think it is working otherwise, though.
=> Added execution service queues

KEYCLOAK-SETUP.md, README.md, scripts/eap-setup.cli
Added pure keycloak and tuned instructions for JMS
=> updating instructions on setup

README.md
Do not install npm packages with sudo, add link to fix permissions issues when installing packages globally as user.
=> Update npm installation instructions in README.md

ui/src/main/webapp/app/app.module.ts, ui/src/main/webapp/app/components/edit-application-form.component.ts, ui/src/main/webapp/app/components/registerapplicationform.component.html, ui/src/main/webapp/app/components/registerapplicationform.component.ts, ui/src/main/webapp/app/components/upload/upload-progressbar.component.html, ui/src/main/webapp/app/components/upload/upload-progressbar.component.ts, ui/src/main/webapp/app/components/upload/upload-queue.component.html, ui/src/main/webapp/app/components/upload/upload-queue.component.ts, ui/src/main/webapp/app/services/registeredapplication.service.ts
Added drag & drop support, file queue and file upload progress bar
=> Advanced upload

services/src/main/java/org/jboss/windup/web/services/RuleDataLoader.java, services/src/main/java/org/jboss/windup/web/services/model/Configuration.java, services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/ConfigurationService.java, services/src/main/webapp/WEB-INF/web.xml, services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/ConfigurationEndpointTest.java, services/src/test/resources/custom-rulesets-data/custom-ruleset.windup.xml, ui/src/main/webapp/app/app.module.ts, ui/src/main/webapp/app/components/analysiscontextform.component.html, ui/src/main/webapp/app/components/analysiscontextform.component.ts, ui/src/main/webapp/app/components/custom-rule-selection.component.html, ui/src/main/webapp/app/components/custom-rule-selection.component.ts, ui/src/main/webapp/app/services/configuration.service.ts
not done, but here is endpoint for getting custom ruleset paths, but UI is still showing me the constant array, which I used for the beginning of the UI creation.
=> Taiga task 237

ui/src/main/webapp/app/app.module.ts, ui/src/main/webapp/app/components/app.component.html, ui/src/main/webapp/app/components/app.component.ts, ui/src/main/webapp/app/components/grouplist.component.ts, ui/src/main/webapp/app/components/notification.component.html, ui/src/main/webapp/app/components/notification.component.ts, ui/src/main/webapp/app/rxjs-operators.ts, ui/src/main/webapp/app/services/notification.service.ts, ui/src/main/webapp/app/services/notification.ts, ui/src/main/webapp/app/services/windup.http.service.ts
Improved error handling - created notification service and component to display notification and error messages. Also added catching error 404 to group list component. Now when error 404 occurs it redirects to main screen and displays error message.
=> Error handling

services/src/main/java/org/jboss/windup/web/services/rest/ErrorMessage.java, services/src/main/java/org/jboss/windup/web/services/rest/ExceptionHandler.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, ui/src/main/webapp/app/components/registerapplicationform.component.html, ui/src/main/webapp/app/components/registerapplicationform.component.ts, ui/src/main/webapp/app/services/registeredapplication.service.ts
Taiga story 287 - bulk registration of applications
=> 287 bulk app registration

KEYCLOAK-SETUP.md, README.md
Some more cleaning and polishing of README.md documentation.
See rendered README.md at https://github.com/mareknovotny/windup-web/tree/readme-updates for quick check.
=> updates/formatting of README.md and KEYCLOAK-SETUP.md

ui/src/main/webapp/app/app.module.ts, ui/src/main/webapp/app/app.routing.ts, ui/src/main/webapp/app/components/app.component.html, ui/src/main/webapp/app/components/reports/technologies/technologies.report.html, ui/src/main/webapp/app/components/reports/technologies/technologies.report.ts
URL: http://localhost:8080/windup-web/technology-report
(not linked from anywhere yet, as there is no functionality)
=> Task300 technologies page structure

ui/src/main/webapp/app/components/modal-dialog.component.ts, ui/src/main/webapp/systemjs.config.js, ui/src/main/webapp/tests/app/components/modal-dialog.component.spec.ts, ui/src/main/webapp/tests/unit-tests.html.ftl, ui/src/main/webapp/typings.json
Fixed bug caused by having different instances of jQuery loaded. Also added test for modal dialog component.
=> Bugfix jstree causing problems with modal dialogs

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResourceImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
Many endpoints were incorrectly returning status code 204 and empty response when requested object didn't exist. I added null check and throwing NotFoundException.
=> Add missing throw NotFoundException.

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpoint.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpointImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/AbstractGraphResource.java, services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java, services/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/rest/RestApplicationFurnace.java, services/src/main/resources/META-INF/persistence.xml, services/src/test/resources/WEB-INF/windupservices-ds.xml, ui/src/main/webapp/package.json, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.service.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/severity-enum.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/type-declarations.d.ts, ui/src/main/webapp/src/app/constants.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts, ui/src/main/webapp/tests/app/mocks/activated-route.mock.ts, ui/src/main/webapp/tests/app/mocks/migration-issues-service.mock.ts
There is some issue with numbers not matching the static report counts. I need to fix that first and I think it will be ready to merge then.
=> Migration Issues Report

KEYCLOAK-SETUP.md, README.md, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtil.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/techreport/TechnologiesStatsEndpoint.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/TypeScriptModelsGeneratingService.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/TypeScriptModelsGeneratorConfig.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/FrameType.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/ModelMember.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/ModelProperty.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/ModelRelation.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/PrimitiveType.java, furnace-service-provider/src/main/java/org/jboss/windup/web/furnaceserviceprovider/FurnaceShutdownEvent.java, services/pom.xml, services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java, services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java, services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpoint.java, services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/ConfigurationEndpointTest.java, settings.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/src/main/java/org/jboss/windup/web/tsmodelgen/WindupTsModelGenMojo.java, tsmodelsgen-maven-plugin/src/main/resources/META-INF/beans.xml, ui/src/main/java/org/jboss/windup/web/ui/FreemarkerServlet.java, ui/src/main/java/org/jboss/windup/web/ui/PathFilter.java, ui/src/main/webapp/src/app/components/popover.component.ts, ui/src/main/webapp/src/app/components/reports/technologies/technologies.report.html, ui/src/main/webapp/tests/app/models/discriminator-mapping-test-data.ts, ui/src/main/webapp/tests/app/models/test-graph-data.ts, ui/src/test/resources/arquillian.xml
git check-whitespace | grep trailing | cut -d: -f1 | sort | uniq | xargs sed -i -E 's/[ \t]*$//'
git ls-files *.java *.ts *.xml *.html -z | xargs -0 -I {} bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0" ' {}
=> Remove trailing whitespace

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/app.component.html, ui/src/main/webapp/src/app/components/app.component.ts, ui/src/main/webapp/src/app/components/group-list.component.html, ui/src/main/webapp/src/app/components/group-list.component.ts, ui/src/main/webapp/src/app/components/group.page.component.ts, ui/src/main/webapp/src/app/components/group/application-group.resolve.ts, ui/src/main/webapp/src/app/components/layout/default-layout.component.html, ui/src/main/webapp/src/app/components/layout/default-layout.component.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.html, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/components/navigation/context-menu-item.class.ts, ui/src/main/webapp/src/app/components/navigation/context-menu.component.html, ui/src/main/webapp/src/app/components/navigation/context-menu.component.ts, ui/src/main/webapp/src/app/components/notification.component.html, ui/src/main/webapp/src/app/components/notification.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.ts, ui/src/main/webapp/src/app/components/reports/technologies/technologies.report.ts, ui/src/main/webapp/src/app/services/logged-in.guard.ts, ui/src/main/webapp/src/app/services/notification.service.ts, ui/src/main/webapp/src/app/services/project.resolve.ts, ui/src/main/webapp/src/app/services/route-link-provider-service.ts, ui/src/main/webapp/src/index.html.ftl, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
Rebased branch with almost no refactorings. 
I removed parts where I changed the way how data are loaded for existing components.
=> 332 - Navigation menu

ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts
Renamed parameter from id to executionId in migration issues table test.
=> Fix broken migration issues table test.

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/analysis-context-form.component.html, ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/application-group-form.component.ts, ui/src/main/webapp/src/app/components/configuration.component.ts, ui/src/main/webapp/src/app/components/edit-application-form.component.ts, ui/src/main/webapp/src/app/components/group-list.component.ts, ui/src/main/webapp/src/app/components/group.page.component.ts, ui/src/main/webapp/src/app/components/group/application-group.resolve.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/components/migration-project-form.component.html, ui/src/main/webapp/src/app/components/migration-project-form.component.ts, ui/src/main/webapp/src/app/components/notification.component.html, ui/src/main/webapp/src/app/components/project-list.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.ts, ui/src/main/webapp/src/app/components/reports/technologies/technologies-report.component.ts, ui/src/main/webapp/src/app/services/application.resolve.ts, ui/src/main/webapp/src/app/services/configuration.resolve.ts, ui/src/main/webapp/src/app/services/notification.service.ts, ui/src/main/webapp/src/app/services/project.resolve.ts, ui/src/main/webapp/src/app/utils.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
Refactored components which require data to be available to use Resolve. 
It simplifies the code of components (no need to handle situation when data are not available) and centralizes error handling - Resolve class is handling both - loading data and errors.
Also Resolve could be used in multiple components.
=> Load data from Resolve

ui/pom.xml
https://github.com/windup/windup-web/pull/106
=> Added a property to help the Jenkins maven plugin find the test results

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtil.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtilImpl.java, services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java, services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/DefaultGraphPathLookup.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, services/src/main/java/org/jboss/windup/web/services/servlet/FileDefaultServlet.java, services/src/main/webapp/WEB-INF/web.xml, services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java
This PR changes directory structure to hierarchical one.
Old structure:
```
+ windup data directory
|    +--- project-id
|    |    +--- group-id
|    |    |    +--- apps
|    |    |    |    +--- some-application.war
|    +--- reports
|    |    +--- Default Group 8a7d8sa.report
|    |    +--- Default Group 64365d2.report
```
New structure:
```
+ windup data directory
|    +--- project-id
|    |    +--- group-id
|    |    |    +--- apps
|    |    |    |    +--- some-application.war
|    |    |    +--- reports
|    |    |    |    +--- report-id-1
|    |    |    |    +--- report-id-2
```
It also allows to have multiple reports for one application group. (Previously when Windup was executed, it removed old report and replaced it with new one).
=> Directory structure

services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java, services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java, services/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, ui/src/main/webapp/src/app/components/confirmation-modal.component.ts, ui/src/main/webapp/src/app/components/group-list.component.html, ui/src/main/webapp/src/app/components/group-list.component.ts, ui/src/main/webapp/src/app/components/project-list.component.html, ui/src/main/webapp/src/app/components/project-list.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts, ui/src/main/webapp/src/app/services/migration-project.service.ts, ui/src/main/webapp/src/app/services/windup.http.service.ts
Add ability to delete project and group.
Note:
I need to take care of deleting files relevant to project/group.
=> Delete project and group

ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/application-group-form.component.html, ui/src/main/webapp/src/app/components/application-group-form.component.ts, ui/src/main/webapp/src/app/components/form.component.ts, ui/src/main/webapp/src/app/components/group-list.component.ts, ui/src/main/webapp/src/app/components/migration-project-form.component.html, ui/src/main/webapp/src/app/components/migration-project-form.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.ts
I fixed project and group create/edit pages. During that I noticed AnalysisContext was broken, so I fixed it as well.
Fixed issues:
https://issues.jboss.org/projects/WINDUP/issues/WINDUP-1249
https://issues.jboss.org/projects/WINDUP/issues/WINDUP-1250
=> Project/Group editing JIRA issues

ui/src/main/webapp/src/app/components/edit-application-form.component.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/components/navigation/context-menu-item.class.ts, ui/src/main/webapp/src/app/components/navigation/context-menu.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts, ui/src/main/webapp/src/app/windup-services.ts
- Make the contextual items appear and disappear more reliably on group changes
- Update context menu to point to the most recent execution, including in progress executions (live data is visible)
- Update all windup-services models
=> Miscellaneous fixes

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/components/AbstractComponent.ts, ui/src/main/webapp/src/app/components/executions/active-executions-progressbar.component.html, ui/src/main/webapp/src/app/components/executions/active-executions-progressbar.component.ts, ui/src/main/webapp/src/app/components/executions/all-executions.component.ts, ui/src/main/webapp/src/app/components/executions/executions-list.component.html, ui/src/main/webapp/src/app/components/executions/executions-list.component.ts, ui/src/main/webapp/src/app/components/executions/executions-monitoring.component.ts, ui/src/main/webapp/src/app/components/executions/group-executions.component.ts, ui/src/main/webapp/src/app/components/group-list.component.ts, ui/src/main/webapp/src/app/components/group.page.component.html, ui/src/main/webapp/src/app/components/group.page.component.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts, ui/src/main/webapp/src/app/services/events/event-bus.service.ts, ui/src/main/webapp/src/app/services/events/windup-event.ts, ui/src/main/webapp/src/app/services/scheduler.service.ts, ui/src/main/webapp/src/app/services/windup-execution.service.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts, ui/src/main/webapp/tests/app/mocks/scheduler-service.mock.ts, ui/src/main/webapp/tests/app/services/events.spec.ts, ui/src/main/webapp/tests/app/services/windup-execution.service.spec.ts
Show list of active executions with progressbar.
- group page
- executions list (group level)
- global executions list
Tasks included in this story:
[442 - Display progress/status of current or most recent exec on group page](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/442)
[443 - Show progress bars for active executions on exec listing pages](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/443)
=> Active executions progressbar

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphResource.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/AbstractGraphResource.java
=> Graph REST API @Incidence support - add edges data to the data tree

ui/src/main/webapp/src/app/components/executions/group-executions.component.ts
While working on rules report I found and fixed bug with group executions missing data.
=> Fix group executions list.

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/components/reports/rule-provider-executions/rule-provider-executions.component.html, ui/src/main/webapp/src/app/components/reports/rule-provider-executions/rule-provider-executions.component.ts, ui/src/main/webapp/src/app/components/reports/rule-provider-executions/rule-provider-executions.service.ts, ui/src/main/webapp/src/app/services/graph.service.ts
- Create new executed rules report
- Provide link to rule from migration issues report 
Depends on https://github.com/windup/windup/pull/1062
=> 430 - rule detail link

ui/src/main/webapp/src/app/components/custom-select/custom-select.component.ts, ui/src/main/webapp/src/app/components/reports/filter/report-filter.component.ts
Fix tags selection - every tag must have unique id.
Solves [Taiga task 480](https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/480?kanban-status=543761)
=> Fix multi-select component.

ui/src/main/webapp/src/app/components/group.page.component.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts, ui/src/main/webapp/src/app/services/events/windup-event.ts, ui/src/main/webapp/src/app/services/registered-application.service.ts, ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts
- Display/hide run windup button right away when application is added/all applications are removed.
=> 473 - Show "Run Windup" button when app added

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/app.component.ts, ui/src/main/webapp/src/app/services/route-history.service.ts, ui/src/main/webapp/tests/app/services/route-history.service.spec.ts
Add RouteHistoryService to store visited routes and enable navigating to previously visited route.
=> Fix cancel() and save() button redirection for analysis context form.

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/model/TagDTO.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/TagResource.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/TagResourceImpl.java, services/src/main/java/org/jboss/windup/web/services/RuleDataLoader.java, services/src/main/java/org/jboss/windup/web/services/TagDataLoader.java, services/src/main/java/org/jboss/windup/web/services/model/Tag.java, ui/src/main/webapp/src/app/components/reports/filter/report-filter.component.ts
- Update Tag entity
- Load tags from TagResource into DB
- Use tags from DB in ReportFilter
=> Fix tags filtering.

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/tsmodelgen/TypeScriptModelsGenerator.java, ui/src/main/webapp/tests/app/components/reports/tag-filter.service.spec.ts
Contains the previous PR as well, by a mistake.
=> Fix TS compiler error

ui/src/main/webapp/src/app/components/project-list/project-list.component.html, ui/src/main/webapp/src/app/components/project-list/project-list.component.scss
=> Update text when filter filters out all projects.

services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/model/ApplicationGroup.java, services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java, services/src/main/java/org/jboss/windup/web/services/model/PackageMetadata.java, services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java, services/src/main/java/org/jboss/windup/web/services/rest/ApplicationGroupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/FileEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/ApplicationGroupService.java, services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java, services/src/main/java/org/jboss/windup/web/services/service/PackageService.java, services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, services/src/test/java/org/jboss/windup/web/services/data/DataProvider.java, services/src/test/java/org/jboss/windup/web/services/data/ServiceConstants.java, services/src/test/java/org/jboss/windup/web/services/data/WindupExecutionUtil.java, services/src/test/java/org/jboss/windup/web/services/rest/ApplicationGroupTest.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointTest.java, ui/src/main/webapp/src/app/components/edit-application-form.component.ts, ui/src/main/webapp/src/app/components/group.page.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts, ui/src/main/webapp/src/app/services/events/windup-event.ts, ui/src/main/webapp/src/app/services/registered-application.service.ts, ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts
- Applications now belong directly to project
- Change relation between application and group to n:n
=> 519 - associate applications under project

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/analysis-context-form.component.html, ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/edit-application-form.component.ts, ui/src/main/webapp/src/app/components/migration-project-form.component.html, ui/src/main/webapp/src/app/components/migration-project-form.component.ts, ui/src/main/webapp/src/app/components/project-list/project-list.component.ts, ui/src/main/webapp/src/app/components/register-application-form.component.html, ui/src/main/webapp/src/app/components/register-application-form.component.ts, ui/src/main/webapp/src/app/components/wizard-component.scss, ui/src/main/webapp/src/app/components/wizard.component.html, ui/src/main/webapp/src/app/components/wizard.component.ts, ui/src/main/webapp/src/app/services/application-group.service.ts
Connect Create Project page to Register Application and to Analysis Configuration.
Provide option to run analysis after saving analysis configuration.
=> 514 - wizard create project

services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointTest.java, ui/src/main/webapp/src/app/components/migration-project-form.component.html, ui/src/main/webapp/src/app/components/migration-project-form.component.ts, ui/src/main/webapp/src/app/components/project-list/project-list.component.html, ui/src/main/webapp/src/app/components/project-list/project-list.component.scss, ui/src/main/webapp/src/app/components/project-list/project-list.component.ts, ui/src/main/webapp/src/app/services/migration-project.service.ts
Also contains T537; it's in the same files so I didn't want to tear the PRs apart.
Therefore depends on PR #202 .
See the 2nd commit only for changes for T537.
=> T536 Add app count to project list

ui/src/main/webapp/src/app/components/project-list/project-list.component.scss
Have a look at how it looks, I think we need this, especially the title is squeezed and when long, trimmed.
=> Giving the title and description more space

ui/src/main/webapp/package.json, ui/src/main/webapp/src/app/components/register-application-form.component.html
This was already done but I am adding one litte thing
=> T523 i182n add app page

ui/src/main/webapp/src/app/components/analysis-context-form.component.ts, ui/src/main/webapp/src/app/components/project-list/project-list.component.html, ui/src/main/webapp/src/app/components/project-list/project-list.component.ts
This is likely to only be temporary until the new page is constructed.
=> Automatically redirect to the group page after the new project is created

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/AggregatedStatisticsEndpoint.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/AggregatedStatisticsEndpointImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/dependencies/LibraryDependenciesService.java, services/src/main/java/org/jboss/windup/web/services/rest/RestApplicationFurnace.java, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/components/layout/group-layout.component.ts, ui/src/main/webapp/src/app/components/reports/application-index/aggregated-statistics.service.ts, ui/src/main/webapp/src/app/components/reports/application-index/application-index.component.css, ui/src/main/webapp/src/app/components/reports/application-index/application-index.component.html, ui/src/main/webapp/src/app/components/reports/application-index/application-index.component.ts, ui/src/main/webapp/src/app/components/reports/application-index/type-declaration.d.ts, ui/src/main/webapp/tests/app/components/reports/application-index/application-index.component.spec.ts
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/us/380
=> Report index report

ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.ts
Before, after. As per PF pattern. IMO needs T565 and T566.
=> T544 Openshiftize Issues report

ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues.component.ts
=> T565 Render markdown in Migr Issues Report

ui/src/main/webapp/src/app/components/reports/source/source-report.component.css, ui/src/main/webapp/src/app/components/reports/source/source-report.component.html, ui/src/main/webapp/src/app/components/reports/source/source-report.component.ts
Quite a lot of improvements of code and hints CSS. Plus the pane CSS.
BEFORE:
=> T546 Openshiftize Source Report

services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/components/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/components/reports/source/source-report.component.ts
Involves a setTimeout() workaround, we need to create some PrismCodeBoxComponent
=> Syntax highlight migration issues T567

ui/src/main/webapp/src/app/components/layout/default-layout.component.html, ui/src/main/webapp/src/app/components/layout/project-layout.component.html
This will be useful to style certain things based on the current layout. I needed this recently for breadcrumbs, as we were discussing during meeting.
=> Add layout CSS classes

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/components/navigation/breadcrumbs.component.html
=> T566 Openshiftize breadcrumbs

services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/shared/checkboxes.component.html, ui/src/main/webapp/src/app/shared/checkboxes.component.ts
I have marked this as ready for review, but really this will likely change once your group removal work is complete.
I was just wondering if you could review the checkboxes stuff in the mean time, though.
=> Task 572: Save & Run and Fixes to App Selection

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/components/in-viewport.directive.ts, ui/src/main/webapp/src/app/reports/application-details/application-details.component.html, ui/src/main/webapp/src/app/reports/application-details/application-details.component.ts
This should improve performance considerably on large reports.
=> Application Details: Lazy load horizontal graphs

services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/analysis-context/package-registry.service.ts, ui/src/main/webapp/src/app/registered-application/registered-application.service.ts, ui/src/main/webapp/tests/app/mocks/scheduler-service.mock.ts, ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts, ui/src/main/webapp/tests/app/services/package-registry.service.spec.ts
- Add endpoint to get PackageMetadata for application
- Add frontend methods to load PackageMetadata
- Add frontend method to keep loading PackageMetadata until status is COMPLETE
- Fix AnalysisContextForm
=> Fix package selection

ui/src/main/webapp/package.json, ui/src/main/webapp/yarn.lock
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript
=> TS upgrade

pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml, tsmodelsgen-maven-plugin/src/it/sample-project/pom.xml
Comes with https://github.com/windup/windup/pull/1084
=> T617 Upgrade Forge and Furnace

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/executions/execution-detail.component.ts, ui/src/main/webapp/src/app/executions/executions-layout.component.html, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/project/project-layout.component.html, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.scss, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.ts, ui/src/main/webapp/src/app/shared/navigation/navbar-selection.component.html, ui/src/main/webapp/src/app/shared/navigation/navbar-selection.component.scss, ui/src/main/webapp/src/app/shared/navigation/navbar-selection.component.ts, ui/src/main/webapp/src/app/shared/navigation/navbar.component.html, ui/src/main/webapp/src/app/shared/navigation/navbar.component.scss, ui/src/main/webapp/src/app/shared/navigation/navbar.component.ts
=> 573 - project report navigation

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/package.json, ui/src/main/webapp/src/vendor.ts, ui/src/main/webapp/yarn.lock
Taiga task #613 - Add an icon to indicate that static reports open in a
new tab/window https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/613?kanban-status=543761
Update font-awesome to include new window icon. Set icon to all `<a>`
tags with `target="_blank"`
=> Add icon indicating link will open in new window

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtilImpl.java, services/src/main/java/org/jboss/windup/web/services/servlet/FileDefaultServlet.java, services/src/main/webapp/WEB-INF/web.xml
replacing `jboss.server.data.dir` and its usage to fallback if `windup.data.dir` is not set
=> task582 - externalize data storage from Wildfly tree

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorService.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java, services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/analysis-context/analysis-context.service.ts, ui/src/main/webapp/src/app/project/migration-project.service.ts, ui/src/main/webapp/src/app/shared/checkboxes.component.ts
Depends on https://github.com/windup/windup/pull/1078
Related to https://github.com/windup/windup-web/pull/271
=> T550 Analysis context page --skipReports checkbox

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/reports/application-index/application-index.component.css, ui/src/main/webapp/src/app/reports/application-index/application-index.component.html, ui/src/main/webapp/src/app/reports/application-index/application-index.component.ts, ui/src/main/webapp/src/app/reports/application-level-layout.component.html, ui/src/main/webapp/src/app/reports/application-level-layout.component.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts
Contains application list in application index report - taiga task #574 - https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/574
Also contains application level navigation.
=> 574 - application index

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/reports/application-details/application-details.component.html, ui/src/main/webapp/src/app/reports/application-index/application-index.component.html, ui/src/main/webapp/src/app/reports/application-level-layout.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues.component.html, ui/src/main/webapp/src/app/reports/source/source-report.component.html, ui/src/main/webapp/src/app/reports/source/source.resolve.ts, ui/src/main/webapp/src/app/shared/navigation/navbar.component.html
Based on https://docs.google.com/document/d/1XeAEmQtg0QDU8rAdAn3PAgY5JN12sEJn8a1WyGNKG6E/edit
=> T484 Titles should be displayed consistently on all pages

pom.xml
the last one for https://issues.jboss.org/browse/WINDUP-1328
=> WINDUP-1328 upgrade of Furnace to 2.25.4.Final

ui/src/main/webapp/src/app/services/windup.service.ts
This causes the caches for executions to be invalidated when a new one is created.
This also prevents the cache from being used while an execution is in progress.
=> Potential fix for cache invalidation issue on executions

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpoint.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/aggregatedStatistics/AggregatedStatisticsEndpoint.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/applicationDetails/ApplicationDetailsResource.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/services/ReportFilterService.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpointImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/aggregatedStatistics/AggregatedStatisticsEndpointImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/applicationDetails/ApplicationDetailsResourceImpl.java, services/src/main/java/org/jboss/windup/web/services/model/ReportFilterDTOImpl.java, services/src/main/java/org/jboss/windup/web/services/service/ReportFilterServiceImpl.java, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/executions/execution.resolve.ts, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/reports/application-details/application-details.component.ts, ui/src/main/webapp/src/app/reports/application-details/application-details.service.ts, ui/src/main/webapp/src/app/reports/application-index/aggregated-statistics.service.ts, ui/src/main/webapp/src/app/reports/application-index/application-index.component.html, ui/src/main/webapp/src/app/reports/application-index/application-index.component.ts, ui/src/main/webapp/src/app/reports/application-level-layout.component.ts, ui/src/main/webapp/src/app/reports/filterable-report.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues.service.ts, ui/src/main/webapp/src/app/shared/abtract.service.ts, ui/src/main/webapp/tests/app/components/reports/application-index/application-index.component.spec.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
This is quick workaround which sends filter in POST data.
Update: Depends on https://github.com/windup/windup-web/pull/293
=> Workaround for app level report filtering

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/reports/application-index/application-index.component.ts, ui/src/main/webapp/src/app/reports/effort-level.enum.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.html, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/tests/app/components/reports/effort-level.enum.spec.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues-table.component.spec.ts
https://issues.jboss.org/browse/WINDUP-1338
=> Adding effort level text into migration issues tables

services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, services/src/test/java/org/jboss/windup/web/services/MigrationProjectAssertions.java, services/src/test/java/org/jboss/windup/web/services/data/WindupExecutionUtil.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/WindupEndpointTest.java
Update lastModified when application is added/updated/removed and when execution is started.
=> Update lastModified field of MigrationProject

ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Column:
- "State" renamed to "Status"
- "Project" and "Date Completed" removed
=> T713_714_717-Executions Page: columns renaming/removing

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/shared/wizard/wizard-component.scss
keeping subtasks on the same branch
=> User story #685 tasks

ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.scss, ui/src/main/webapp/src/app/configuration/configuration.component.ts
- Rename Global Configuration to Rules Configuration
- Move buttons to right
- Remove force reload configuration button
=> 745 - global configuration page

services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java
The deletion from fs didn't work because the File.delete() works only on empty dir that is not our case.
=> T771 fix project deletion from fs

ui/src/main/webapp/src/app/project/project-list.component.html, ui/src/main/webapp/src/app/project/project-list.component.ts, ui/src/main/webapp/src/app/shared/confirmation-modal.component.ts
I don't get how <foo #something >works in Angular2. The docs say I can refer to it anywhere in the template. When I do, it's not defined. See the modal component's #confirmInput and {{confirmInput.value}}.
=> T683 delete project modal confirm

ui/src/main/webapp/src/app/shared/confirmation-modal.component.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
CSS classes for yes/no buttons were changed but tests were not
adjusted for that change. This PR fixes it.
=> Fix broken tests

ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.ts
Taiga task #776 - Delete a user rule path doesn't work
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/776?kanban-status=543761
=> Fix remove rules confirmation dialog

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorService.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java, services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/model/AnalysisContext.java, services/src/main/resources/migration-paths/migration-paths.xml, services/src/test/java/org/jboss/windup/web/services/rest/AnalysisContextEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationPathEndpointTest.java, ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/701
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/703
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/707
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/706
=> Taiga story700 tasks

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html
The latest missing change in helper text for Included packages selection
=> story700: added more descriptive text to Included packages

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
Pending until the one on the analysis context page can be fixed.
=> Task 777: Back and next buttons work

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/project/project-layout.component.html, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/shared/wizard/wizard.component.html
- this moves wizard related styles from forms to actual wizard
- also some other style fixes
=> Fix non wizard mode

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/execution-detail.component.ts, ui/src/main/webapp/src/app/shared/expand-collapse.component.html, ui/src/main/webapp/src/app/shared/expand-collapse.component.ts
Use that component in AnalysisContextForm and ExecutionDetail
component.
=> Create expand/collapse component.

ui/src/main/webapp/src/app/executions/execution-detail.component.html
=> Added passive form into included and excluded packages

ui/src/main/webapp/src/index.html.ftl
Temporary solution. CSS can be pulled in in a smarter way, but it seemed PF is not ready at the time this is loading.
This also removes the thin line (actually a border around the whole Loading... area)
=> Index - Loading... - add fake navbar

ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.ts, ui/src/main/webapp/src/app/shared/navigation/navbar.component.html
Slides 16 to 22.
Some things missing, see the  #comments. (Mostly functional)
https://docs.google.com/presentation/d/1ijAWBKBJi90j6eCjHdkk-y22gGjzJZ2J7XVQcZejaiI/edit#slide=id.g1d8fe0edb4_0_44
=> Marc 2017-04-24 texts, styles etc.

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/project/migration-project.service.ts, ui/src/main/webapp/src/app/registered-application/application-queue-list.component.html, ui/src/main/webapp/src/app/registered-application/application-queue-list.component.ts, ui/src/main/webapp/src/app/registered-application/edit-application-form.component.ts, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts, ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
Show both existing applications and upload queue in the same UI.
Existing applications can be deleted right from the queue.
(I don't really like that solution much, it feels kind of hacky, but I couldn't come up with anything better at the moment).
=> 783 - registered apps form

ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
I also fixed a test broken from a previous commit.
=> T868 Remove active executions from the applications list

ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/src/app/executions/project-executions.component.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
I used the [WindupExecutionService.execute](https://github.com/mrizzi/windup-web/blob/master/ui/src/main/webapp/src/app/services/windup-execution.service.ts#L28) method as it is used in [AnalysisContextFormComponent](https://github.com/mrizzi/windup-web/blob/master/ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts#L302) including all the called methods.
The button is working because it starts an analysis but if there are unnecessary methods, just let me now and I'll fix the code.
The things not working for which i need your help are:
=> T881 Add Run Analysis Button to the top right of the table

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/LogServiceImpl.java
Create local date and time based on millis from LogRecord
=> T872 Analysis detail page, Log tab: add timestamps to the log

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
and add link to Registering application if wanted
=> task848: adding empty page on Configuration page if there is no uploaded Apps

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/shared/is-route-active.directive.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
Create directive `IsRouteActiveDirective` which sets CSS class to element, if `routerLink` attribute matches currently active route.
=> 857 - context menu active class

ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/shared/layout/wizard-layout.component.html
Make wizard inner frame smaller
Taiga task 811
After:
[![Screenshot from 2017-04-28 16-15-52.png](https://s12.postimg.org/o4uat8vil/Screenshot_from_2017-04-28_16-15-52.png)](https://postimg.org/image/4zr1jhguh/)
=> 811 - wizard inner frame

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts, ui/src/main/webapp/src/app/registered-application/edit-application-form.component.ts, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
Various fixes for wizard and wizard steps.
- handle RegisterApp errors as global errors (displayed on top with close button)
- fix form submit for server path (when there are existing applications)
- update AnalysisContextForm loading status for packages
- do not make project title help text red, when form is invalid
=> 808 - wizard fixes

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.scss, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/executions/executions-list.component.html
- "Active analysis" bar is aligned with "Analysis" header
- header of pages Analysis, Application and Configurations are all aligned
=> T886 Align Active analysis to Analysis list

ui/src/main/webapp/src/app/executions/project-executions.component.html, ui/src/main/webapp/src/app/executions/project-executions.component.ts
=> 856 - Create analysis list empty page

services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/AnalysisContextService.java, services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/graph/AbstractGraphResourceTest.java, ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts, ui/src/main/webapp/src/app/project/migration-project.service.ts, ui/src/main/webapp/src/app/shared/validators/project-name-not-exists.validator.ts
SQL:
ALTER TABLE migrationproject DROP COLUMN IF EXISTS provisional;
ALTER TABLE migrationproject ADD COLUMN provisional BOOLEAN DEFAULT FALSE NOT NULL;
Copy the result of this:
SELECT UNIQUE_INDEX_NAME FROM INFORMATION_SCHEMA.CONSTRAINTS WHERE TABLE_NAME = 'MIGRATIONPROJECT' AND COLUMN_LIST = 'TITLE';
And use it here:
ALTER TABLE migrationproject DROP CONSTRAINT xxx;
UPDATE TABLE migrationproject SET title = title + "-pad" WHERE LENGTH(title) < 3
=> S757, T815 - provisional flag for projects

services/src/main/java/org/jboss/windup/web/services/model/MigrationProject.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/MigrationProjectService.java, ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts
I rebased my PR to see what's was thrown away. Commented inline.
// This is not a normal PR, the only things suggested to bring in are those which I commented.
Update: I have cleared it up and now it's a normal PR in terms I am proposing these changes.
=> S757 Leftovers

ui/src/main/webapp/src/app/executions/executions-monitoring.component.ts, ui/src/main/webapp/src/app/registered-application/application-list.component.html
=> 897 - application list empty page

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/core/authentication/logout.guard.ts, ui/src/main/webapp/src/app/project/project-layout.component.html, ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/shared/layout/default-layout.component.html, ui/src/main/webapp/src/app/shared/layout/default-layout.component.ts, ui/src/main/webapp/src/app/shared/layout/wizard-layout.component.html, ui/src/main/webapp/src/app/shared/layout/wizard-layout.component.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.ts, ui/src/main/webapp/src/app/shared/navigation/hamburger-menu.component.html, ui/src/main/webapp/src/app/shared/navigation/hamburger-menu.component.scss, ui/src/main/webapp/src/app/shared/navigation/hamburger-menu.component.ts, ui/src/main/webapp/src/app/shared/navigation/navbar.component.html, ui/src/main/webapp/src/app/shared/navigation/navbar.component.scss, ui/src/main/webapp/src/app/shared/navigation/navbar.component.ts, ui/src/main/webapp/src/app/shared/navigation/navigation-responsive-styles.scss
- Taiga task #898
- copy OpenShift styles and hide icons for width < 1600px
- use hamburger icon and toggleable navigation menu
=> 898 - Improve responsiveness of navigation

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/project/project-list.component.html, ui/src/main/webapp/src/app/project/project-list.component.scss, ui/src/main/webapp/src/app/shared/text/shorten.pipe.ts
See screenshot below
[![Screenshot from 2017-05-05 15-43-55.png](https://s30.postimg.org/a6zfdjr8h/Screenshot_from_2017-05-05_15-43-55.png)](https://postimg.org/image/odf68s23h/)
=> 899 - fix project list responsiveness

ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.html, ui/src/main/webapp/src/app/shared/form.component.ts
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/892?kanban-status=543760
=> task892: disabling Add button until form is valid

ui/src/main/webapp/src/app/shared/navigation/navbar-selection.component.scss
Fixes taiga task #785 - Breadcrumb navigation cannot scroll.
=> 785 - Add scrollbar to breadcrumb navigation

ui/src/main/webapp/src/app/shared/log-view/log-view.component.html, ui/src/main/webapp/src/app/shared/log-view/log-view.component.scss, ui/src/main/webapp/src/app/shared/log-view/log-view.component.ts
I also added a TO-DO for having a better UX when new API will be implemented from Chrome 
https://github.com/windup/windup-web/compare/master...mrizzi:taiga_T871?expand=1#diff-58e1f1be884ba7fa0d9fee733c4a6927R29
=> T871 Analysis details - Log tab: add follow/unfollow buttons

services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointImpl.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectEndpointTest.java, services/src/test/java/org/jboss/windup/web/services/rest/graph/AbstractGraphResourceTest.java, ui/src/main/webapp/src/app/project/migration-project.service.ts, ui/src/main/webapp/src/app/project/project-list.component.html, ui/src/main/webapp/src/app/project/project-list.component.scss, ui/src/main/webapp/src/app/project/project-list.component.ts
Disables delete button on project when analysis is running
=> 844 - delete project while analysis running

ui/src/main/webapp/src/app/shared/navigation/navbar.component.html
row 30
Existing Text	|Suggested Text	|Notes
---------- | ---------- | ----------
Logout	|Log Out	|The action to log out is two words
=> T945 Log Out in user drop down

ui/src/main/webapp/src/app/shared/navigation/navbar.component.html, ui/src/main/webapp/src/index.html.ftl
row 5
Existing Text	|Suggested Text	|Notes
---------- | ---------- | ----------
__RED HAT APPLICATION MIGRATION TOOLKIT__ - Web Console	|__RED HAT APPLICATION MIGRATION TOOLKIT__ Web Console	|Remove dash, you already bold/unbold to differentiate
=> T939 Black banner: change texts

ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.ts
`AnalysisContextAdvancedOptionsModalComponent.availableOptions` method now returns a `ConfigurationOption` array sorted by `ConfigurationOption.name`
=> T957 Alphabetize advanced options

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html
rows 10-14
Existing Text	|Suggested Text	|Notes
---------- | ---------- | ----------
Enter the server path containing your project applications.	|File system path that contains the applications	| * No punctuation on field labels  * Prefer "file system path" to "server path"
The input path must exist on the server.	|The file system path must exist on the server. 	|
Directory Contains Multiple Apps	|Directory contains multiple applications	|
If box is checked, the given path will be treated as a directory with multiple applications. Otherwise, the path will be treated as a single application.	|If checked, the given path is treated as a directory with multiple applications. Otherwise, the path is treated as a single application.	|
Choose files	|Choose Files	|Buttons are title case
For the …
=> T943 Project wizard - Add Applications: text changes

services/src/main/resources/migration-paths/migration-paths.xml, services/src/test/java/org/jboss/windup/web/services/rest/MigrationPathEndpointTest.java, ui/src/main/webapp/src/app/analysis-context/analysis-context-advanced-options-modal.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
=> 944 - Fix analysis context form wording

ui/src/main/webapp/src/app/shared/confirm-deactivate.guard.ts
=> 946 - Update confirm leave page dialog.

ui/src/main/webapp/src/app/executions/execution-detail.component.ts, ui/src/main/webapp/src/app/executions/executions-list.component.ts
In #379 i filtered the deleted applications but it's not the right way to count and list the applications involved in an analysis: even if application is deleted it still has to be in the list of the analyzed applications (and increment the counter of applications in analysis list page)
=> T959Application list & details: deleting an application, application counter is decremented

ui/src/main/webapp/src/app/app.routing.ts, ui/src/main/webapp/src/app/project/migration-project-form.component.html, ui/src/main/webapp/src/app/project/migration-project-form.component.ts
rows 8-9
Existing Text	|Suggested Text	|Notes
---------- | ---------- | ----------
Create new Project	|Create Project	|"new" is unnecessary and incorrectly capitalized
my-project	|My Project	|More user-friendly example
=> T942 Project wizard - Create project step: text changes

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/executions/active-executions-progressbar.component.html, ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/src/app/executions/project-executions.component.html, ui/src/main/webapp/src/app/misc/about.component.html, ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/src/app/registered-application/application-list.component.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/us/934 and few tasks from it
=> Several text changes for story 934

ui/src/main/webapp/src/app/project/no-projects-welcome.component.html, ui/src/main/webapp/src/app/project/project-list.component.html, ui/src/main/webapp/src/app/project/project-list.component.ts, ui/src/main/webapp/src/app/shared/dialog/confirmation-modal.component.html
=> Project list texts

ui/src/main/webapp/src/app/shared/dialog/confirmation-modal.component.html
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/976
=> taiga task 976: show confirm modal text styled as pre

ui/src/main/webapp/src/app/analysis-context/custom-rule-selection.component.html
Taiga task #966 - Disable section Custom rulesets on
Configuration Analysis page form if there is no rulesets.
=> Disable custom rules buttons when there are no custom rules.

services/src/main/java/org/jboss/windup/web/services/rest/ErrorInfo.java, services/src/main/java/org/jboss/windup/web/services/rest/ExceptionHandler.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupWebException.java, services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/registered-application/application-queue-list.component.html, ui/src/main/webapp/src/app/registered-application/register-application-form.component.scss, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts, ui/src/main/webapp/src/app/registered-application/registered-application.service.ts, ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.html, ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.scss, ui/src/main/webapp/src/app/shared/upload/alternative-upload-queue.component.ts, ui/src/main/webapp/src/app/shared/upload/file-uploader-wrapper.service.ts
- updated error handling for duplicate file (now it shows error in progressbar)
- centered drop files here text
- some spacing adjustments
- updated wording (file size is now in parentheses)
Currently missing in this PR:
- centering of icons
<s>
Update:
I just noticed there is some bug in file upload introduced by this PR. It behaves very strangely especially when multiple files are selected. I'm trying to find out what is going on.
</s>
=> 816 file upload panel

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtil.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/WebPathUtilImpl.java, services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java, services/src/main/java/org/jboss/windup/web/services/model/RegistrationType.java, services/src/main/java/org/jboss/windup/web/services/model/RulesPath.java, services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/FileAlreadyExistsException.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/ConfigurationService.java, services/src/main/java/org/jboss/windup/web/services/service/FileUploadService.java, services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, ui/src/main/webapp/src/app/components/app.component.ts, ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.html, ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.scss, ui/src/main/webapp/src/app/configuration/add-rules-path-modal.component.ts, ui/src/main/webapp/src/app/configuration/configuration.component.ts, ui/src/main/webapp/src/app/configuration/rule.service.ts, ui/src/main/webapp/src/app/shared/shared.module.ts, ui/src/main/webapp/src/app/shared/upload/file-uploader-factory.service.ts, ui/src/main/webapp/src/app/shared/upload/uploaded-items-list.component.html, ui/src/main/webapp/src/app/shared/upload/uploaded-items-list.component.ts
Taiga task 980 - add upload of custom rules.
=> 980 - upload custom rules

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
when "Save & Run" is clicked before finishing package analysis.
Taiga task #988.
=> 988 - Add confirmation dialog to AnalysisContext form

ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts, ui/src/main/webapp/src/app/shared/form.component.ts
=> 989 - Disable "Upload" button for invalid path in RegisterApp form.

ui/src/main/webapp/src/app/configuration/configuration.component.html
are no rules
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/990
=> task 990 - disabling button Show Rules if there

services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
Do not allow user to register invalid path. 
Also add path check and better error message to backend.
#close WINDUP-1389
=> Fix "Server Path" file upload

ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/src/app/project/project-list.component.html, ui/src/main/webapp/src/app/project/project-list.component.ts, ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/src/app/registered-application/application-list.component.ts
Taiga task #958.
Adds delete spinner for:
- project deletion on project list
- application deletion on app list
- analysis deletion on analysis list
[![Screenshot from 2017-05-30 14-49-45.png](https://s21.postimg.org/9zql6cw7r/Screenshot_from_2017-05-30_14-49-45.png)](https://postimg.org/image/s2jnxks2b/)
=> 958 - Add loading indicator for delete actions

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html
closes WINDUP-1421 and WINDUP-1422
=> Remove unnecessary scrollbars

ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
Show the same path registered multiple times only once.
Do not show any duplicities.
#close WINDUP-1388
=> Filter duplicities in "Server Path" file upload

services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java, services/src/main/java/org/jboss/windup/web/services/model/RegisteredApplication.java, services/src/main/java/org/jboss/windup/web/services/rest/FileEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/FileEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/FileUploadService.java, services/src/main/java/org/jboss/windup/web/services/service/RegisteredApplicationService.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, services/src/test/java/org/jboss/windup/web/services/rest/MigrationProjectRegisteredApplicationsEndpointTest.java, ui/src/main/webapp/src/app/registered-application/register-application-form.component.html, ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts, ui/src/main/webapp/src/app/registered-application/registered-application.service.ts, ui/src/main/webapp/src/app/services/file.service.ts, ui/src/main/webapp/src/app/shared/validators/dir-has-files.validator.ts, ui/src/main/webapp/src/app/shared/validators/file-exists.validator.ts, ui/src/main/webapp/tests/app/components/executions/executions-data.ts, ui/src/main/webapp/tests/app/registeredapplication.service.spec.ts
This covers T818 and also adds a validator which checks if the server path, if it is a directory, contains some Java EE archives.
=> T818 register server path remove checkbox

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts
- Also add spinner icon to signalize progress
#close WINDUP-1420
=> Disable "Save" and "Save & Run" buttons while request in progress

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.ts, ui/src/main/webapp/src/app/reports/dependencies/dependencies-graph.component.css, ui/src/main/webapp/src/app/shared/filter/active-filters-list.component.html, ui/src/main/webapp/src/app/shared/filter/active-filters-list.component.ts, ui/src/main/webapp/src/app/shared/filter/text-filter.component.html, ui/src/main/webapp/src/app/shared/filter/text-filter.component.ts, ui/src/main/webapp/src/app/shared/shared.module.ts, ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.html, ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.scss, ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.ts
- filtering by `source` or `target` technology (for now only text based without version support, I'll create separate PR for it)
- sorting by:
- name
- count of rules
- date created
- last modified
=> Add filtering and sorting to rules configuration

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java
<s>I tried the approach with filter in server config, but it didn't work.
This solution works, but I need to verify if it doesn't have any side effects, like unintentional loss of logging. 
</s>
I also found bug with missing `flush` which caused analysis logs to be incomplete in some cases. 
Update: I removed log filtering from this PR and moved it to https://github.com/windup/windup-web-distribution/pull/22
Now only the flush part is here.
=> Add flush to analysis log handler

ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/src/app/shared/is-route-active.directive.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu-item.class.ts, ui/src/main/webapp/src/app/shared/navigation/context-menu.component.html
- fix "Analysis" highlighting in context menu
- fix project highlighting in project-level navbar
=> WINDUP-1442 - highlight analysis context menu

ear/pom.xml, ear/src/main/application/META-INF/jboss-deployment-structure.xml
https://issues.jboss.org/browse/WINDUP-1392
=> WINDUP-1392: fixed module names in EAR

services/src/main/java/org/jboss/windup/web/services/RuleDataLoader.java, services/src/main/java/org/jboss/windup/web/services/service/ConfigurationService.java, ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/shared/replace.pipe.ts
https://issues.jboss.org/browse/WINDUP-1446
Example how it is rendered:
=> WINDUP-1446: filter and format invalid ruleset paths

ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/src/app/registered-application/application-list.component.ts, ui/src/main/webapp/src/app/shared/all-data-filtered-message.component.html, ui/src/main/webapp/src/app/shared/all-data-filtered-message.component.ts, ui/src/main/webapp/src/app/shared/shared.module.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
=> Add 'Filter is hiding all items' message to tables.

ui/src/main/webapp/css/windup-web.css, ui/src/main/webapp/src/app/shared/navigation/navbar.component.scss, ui/src/main/webapp/src/app/shared/navigation/navigation-responsive-styles.scss
Link: https://docs.google.com/presentation/d/1ijAWBKBJi90j6eCjHdkk-y22gGjzJZ2J7XVQcZejaiI/edit#slide=id.g1e7812a07c_0_25
=> Slide 11: Left Nav icons are not padded as in Patternfly

ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.scss, ui/src/main/webapp/src/app/configuration/configuration.component.ts, ui/src/main/webapp/src/app/shared/filter/dropdown-filter.component.html, ui/src/main/webapp/src/app/shared/filter/dropdown-filter.component.ts, ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.html, ui/src/main/webapp/src/app/shared/toolbar/toolbar.component.ts
- WINDUP-1474 is fully done - filtering is now on the same line as title
- WINDUP-1473 - spacing is reduced, missing parts are:
- update error messages
- add link to documentation
[![page-screen-filters.png](https://s8.postimg.org/d2frt4ld1/page-screen-filters.png)](https://postimg.org/image/yousa5jxd/)
=> Windup 1472 rules configuration

services/src/main/java/org/jboss/windup/web/services/rest/UnhandledExceptionHandler.java
Reverts windup/windup-web#470
This shouldn't be merged to master yet.
=> Revert "Change "Database constraints were not met." to something more general…"

services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, ui/src/main/webapp/src/app/registered-application/application-list.component.html, ui/src/main/webapp/src/app/registered-application/application-list.component.ts, ui/src/main/webapp/src/app/registered-application/registered-application.service.ts
=> Add file download for applications

services/src/main/java/org/jboss/windup/web/services/model/RuleProviderEntity.java, services/src/main/java/org/jboss/windup/web/services/rest/ConfigurationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, ui/src/main/webapp/src/app/configuration/configuration.component.html, ui/src/main/webapp/src/app/configuration/configuration.component.ts, ui/src/main/webapp/src/app/configuration/rule.service.ts
https://issues.jboss.org/browse/WINDUP-1470
=> WINDUP-1470: fixing removal of custom ruleset

ui/src/main/webapp/src/app/app.module.ts, ui/src/main/webapp/src/app/configuration/rule.service.ts, ui/src/main/webapp/src/app/shared/upload/file-uploader-factory.service.ts, ui/src/main/webapp/src/app/shared/upload/file-uploader-wrapper.service.ts
The `token` is now refreshed just before starting the upload of a file.
Thanks to @jsight for the help.
=> WINDUP-1553 File Upload time out fix

services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, services/src/main/java/org/jboss/windup/web/services/servlet/FileDefaultServlet.java
Fixes displayed error message for deleted (or non-existing) report.
(I assume this fix should go to 4.0.x branch, we will want it to be in GA version too)
=> WINDUP-1571 - Fix error 404 handling for static reports

ui/src/main/webapp/src/app/reports/migration-issues/problem-summary-files.component.html, ui/src/main/webapp/src/app/reports/migration-issues/problem-summary-files.component.ts
Depends on https://github.com/windup/windup/pull/1151
=> WINDUP-1588 - Load full path for migration issues file

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/MigrationIssuesEndpoint.java, addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/HardcodedIPResource.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/HardcodedIPResourceImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RestApplicationFurnace.java, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/reports/application-level-layout.component.ts, ui/src/main/webapp/src/app/reports/hardcoded-ip/hardcoded-ip.component.html, ui/src/main/webapp/src/app/reports/hardcoded-ip/hardcoded-ip.component.scss, ui/src/main/webapp/src/app/reports/hardcoded-ip/hardcoded-ip.component.ts, ui/src/main/webapp/src/app/reports/hardcoded-ip/hardcoded-ip.service.ts, ui/src/main/webapp/src/app/reports/reports-routing.module.ts, ui/src/main/webapp/src/app/reports/reports.module.ts, ui/src/main/webapp/src/app/reports/source/source-report.component.html, ui/src/main/webapp/src/app/reports/source/source-report.component.ts, ui/src/main/webapp/src/app/services/graph/classification.service.ts, ui/src/main/webapp/src/app/services/graph/hint.service.ts
Basic functionality is there (based upon Marco's PR).
=> Windup 1581: Hardcoded IP Report

ui/src/main/webapp/src/app/reports/application-level-layout.component.html
Aligned title for application-layout reports to the one of execution-layout reports.
=> WINDUP-1655: alignment of title for application level reports

addons/web-support/api/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/RemoteServicesResource.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/AbstractGraphResource.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/HibernateResourceImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/RemoteServicesResourceImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RestApplicationFurnace.java, ui/src/main/webapp/src/app/executions/executions-layout.component.ts, ui/src/main/webapp/src/app/reports/application-level-layout.component.ts, ui/src/main/webapp/src/app/reports/reports-routing.module.ts, ui/src/main/webapp/src/app/reports/reports.module.ts, ui/src/main/webapp/src/app/reports/technologies/remote-services/remote-services-report.component.html, ui/src/main/webapp/src/app/reports/technologies/remote-services/remote-services-report.component.ts, ui/src/main/webapp/src/app/reports/technologies/tech-report.service.ts, ui/src/main/webapp/src/app/shared/utils.ts
Depends on https://github.com/windup/windup-web/pull/509
=> WINDUP-1582 remote services

ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.html, ui/src/main/webapp/src/app/reports/execution-application-list/execution-application-list.component.ts, ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.html, ui/src/main/webapp/src/app/reports/technologies/technologies-report-ejb.component.ts
- Use wu-table in EJB reports
- Update application list styles - have search box on right side as everywhere else
=> Use wu-table in EJB reports

ui/src/main/webapp/src/app/configuration/configuration.component.html
https://issues.jboss.org/browse/WINDUP-1573
=> WINDUP-1573: reformat error from parsing custom ruleset

ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
https://github.com/windup/windup/pull/1182
=> WINDUP-1679: Allow .zip in order to allow uploading src applications

ui/src/main/webapp/src/index.html.ftl
https://issues.jboss.org/browse/WINDUP-1691
adding meta header for UTF-8 content
=> WINDUP-1691: adding encoding of pages

ui/src/main/webapp/src/app/core/authentication/logged-in.guard.ts, ui/src/main/webapp/src/app/reports/migration-issues/problem-summary-files.component.html, ui/src/main/webapp/src/app/reports/migration-issues/problem-summary-files.component.ts
This should fix issues with navigation to executed rule report with specified rule ID.
=> WINDUP-1466 - fix executed rule report navigation

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/LogServiceImpl.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java
Porting #532 to 4.0.x branch w/ 1 exception for file [StatusUpdateMDB.java](https://github.com/windup/windup-web/pull/532/files#diff-6dd42f8bf09d10498bf0d05c8bfc7601) because it was conflicting so no changes to it in this PR (they were just some unused import cleaning in master branch)
=> WINDUP-1749: Reduce the loggin (#532)

ui/src/main/webapp/src/app/configuration/rules-modal.component.ts, ui/src/main/webapp/src/app/executions/execution-detail.component.ts, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/src/app/executions/project-executions.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/migration-issues-table.component.ts, ui/src/main/webapp/src/app/reports/migration-issues/problem-summary-files.component.ts, ui/src/main/webapp/src/app/shared/js-tree-angular-wrapper.component.ts, ui/src/main/webapp/src/app/shared/notification.component.ts, ui/src/main/webapp/tests/app/components/reports/migration-issues/migration-issues.component.spec.ts
SchedulerService provides more convenient way of running these async
callbacks and internally implements setInterval, setTimeout functions
to run outside of angular zone. This is required for protractor tests.
Also SchedulerService provides easier testability and maintainability.
(Separated from PR #527 )
=> Use SchedulerService for all setTimeout/setInterval calls

ui/src/main/webapp/src/app/shared/is-route-active.directive.ts, ui/src/main/webapp/src/app/shared/navigation/hamburger-menu.component.html
Backport of PR #536 to 4.0.x branch
=> WINDUP-1781 - broken highlighting (for 4.0.x)

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/ProjectLoaderServiceImpl.java
Porting of #540 to `master` branch
=> Remove useless log

ui/src/main/webapp/src/app/project/project-layout.component.ts, ui/src/main/webapp/tests/app/components/project/project-layout.component.spec.ts
I also added test for this, but test currently doesn't work. It doesn't even execute, for some reason it fails in very early phase, probably during loading dependencies. So far I don't know why :(
Error message isn't helpful either
```
TypeError: undefined: can't set as prototype!
at webpack:///~/core-js/modules/_set-proto.js:7:0 <- config/karma-test-shim.js:67465
```
=> WINDUP-1786 Fixed project label changes when analysis running

services/src/main/java/org/jboss/windup/web/services/RuleDataLoader.java, services/src/test/java/org/jboss/windup/web/services/RuleDataLoaderTest.java, services/src/test/resources/custom-rulesets-data/custom-ruleset.rhamt.xml
Fix for the issue and enhancement for the test to cover this case.
=> WINDUP-1839 Upload XML rules '.rhamt.xml'

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java, services/src/main/java/org/jboss/windup/web/services/messaging/WindupExecutionTask.java
Followup on fix for master here: https://github.com/windup/windup-web/pull/550
=> Updated to properly handle lists of advanced options

addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/MessagingProgressMonitor.java, model/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/tests/app/components/executions/executions-data.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
https://issues.jboss.org/browse/WINDUP-1869
=> Windup 1869

ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.html
Extension to https://github.com/windup/windup-web/pull/549
I will backport to the 4.0.x PR as well.
=> WINDUP-1869: Fixed cancellation duration in some edge cases

services/src/main/java/org/jboss/windup/web/services/WindupWebProgressMonitor.java, services/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/service/WindupExecutionService.java, ui/src/main/webapp/src/app/executions/execution-detail.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.html, ui/src/main/webapp/src/app/executions/executions-list.component.ts, ui/src/main/webapp/tests/app/components/executions/executions-data.ts, ui/src/main/webapp/tests/app/components/executions/executions-list.component.spec.ts
Backport of this: https://github.com/windup/windup-web/pull/549
=> Windup 1869 4.0.x backport

addons/messaging-executor/api/src/main/java/org/jboss/windup/web/messaging/executor/ExecutionSerializerRegistry.java, addons/messaging-executor/impl/pom.xml, addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/AbstractSerializer.java, addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/DefaultExecutorBootstrap.java, addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/HttpPostSerializer.java, addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/MessagingSerializer.java, addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/GraphCacheImpl.java, services/src/main/java/org/jboss/windup/web/services/KeycloakAuthenticator.java, services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java, services/src/main/java/org/jboss/windup/web/services/rest/RegisteredApplicationEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpoint.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/websocket/ExecutionProgressReporter.java, services/src/main/webapp/WEB-INF/web.xml, tests/test-authentication-client/src/main/java/org/jboss/windup/web/tests/authentication/KeycloakAuthenticationHelper.java
Just an experiment... needs to be documented and planned out fully to integrate into the regular build.
=> Experimental http serializer support

ui/src/main/webapp/src/app/registered-application/register-application-form.component.ts
https://issues.jboss.org/browse/WINDUP-1981
Also fixes some edge cases around removing already uploaded applications.
=> WINDUP-1981: Do not allow continuing in the wizard if uploads are in progress

addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/HttpPostSerializer.java, addons/messaging-executor/impl/src/main/java/org/jboss/windup/web/messaging/executor/MessagingProgressMonitor.java, services/src/main/java/org/jboss/windup/web/services/messaging/StatusUpdateMDB.java, services/src/main/java/org/jboss/windup/web/services/rest/WindupEndpointImpl.java
Not quite ready for review... still testing. Maybe you can try it out as well, @mrizzi ?
=> WINDUP-2084: Add more debugging code and make sure that the executor removes transient files

build/release_windup_web.sh
https://issues.jboss.org/browse/WINDUP-2086
=> WINDUP-2086 Enhance release script to work with windup-openshift project

ui/src/main/webapp/package.json, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.html, ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/shared/js-tree-angular-wrapper.component.ts
nb - this PR commit is to give Jess an idea of where I am so he can possibly help
=> WINDUP-2024 WIP fao Jess

ui/src/main/webapp/src/app/misc/about.component.html, ui/src/main/webapp/src/app/project/no-projects-welcome.component.html, ui/src/main/webapp/src/app/shared/navigation/hamburger-menu.component.ts, ui/src/main/webapp/src/app/shared/navigation/navbar.component.html
=> WINDUP-1793 Links redirected 

ui/src/main/webapp/package.json, ui/src/main/webapp/src/app/shared/navigation/navbar-selection.component.scss
upgraded version to be node 10 compatible
fixed a minor syntax error
=> Fixed problem with node 10 after upgrade to Fedora 29

services/pom.xml
https://issues.jboss.org/browse/WINDUP-2238
=> WINDUP-2238 Fix warnings when launching web console

LICENSE
https://issues.jboss.org/browse/WINDUP-2370
=> WINDUP-2370 Create LICENSE

ui/src/main/webapp/src/app/analysis-context/analysis-context-form.component.ts, ui/src/main/webapp/src/app/analysis-context/select-packages/select-packages.component.ts
Added an observable to be sure that all @Inputs are already initialized and avoid processing the tree.
=> Windup 2408 - Package Selection - Application Packages not checked for selection by default

pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml
https://issues.redhat.com/browse/WINDUP-2510
=> WINDUP-2510 Bump Furnace version to 2.28.4.Final

addons/messaging-executor/addon/pom.xml, addons/messaging-executor/api/pom.xml, addons/messaging-executor/impl/pom.xml, addons/messaging-executor/pom.xml, addons/messaging-executor/tests/pom.xml, addons/pom.xml, addons/web-support/addon/pom.xml, addons/web-support/api/pom.xml, addons/web-support/impl/pom.xml, addons/web-support/pom.xml, addons/web-support/tests/pom.xml, ear/pom.xml, executor/pom.xml, furnace-service-provider/pom.xml, model/pom.xml, pom.xml, services/pom.xml, tests/e2e/pom.xml, tests/pom.xml, tests/test-authentication-client/pom.xml, tests/wildfly-dist/pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml, ui/pom.xml
https://issues.redhat.com/browse/WINDUP-2667
=> WINDUP-2667: version upgrade

ui/src/main/webapp/src/app/configuration/configuration-labels/configuration-labels.component.html, ui/src/main/webapp/src/app/configuration/configuration-rules/configuration-rules.component.html
https://issues.redhat.com/browse/WINDUP-2674
=> WINDUP-2674: Web-Console UI : Filtering rules by source does not seem to be filtering results

addons/messaging-executor/addon/pom.xml, addons/messaging-executor/api/pom.xml, addons/messaging-executor/impl/pom.xml, addons/messaging-executor/pom.xml, addons/messaging-executor/tests/pom.xml, addons/pom.xml, addons/web-support/addon/pom.xml, addons/web-support/api/pom.xml, addons/web-support/impl/pom.xml, addons/web-support/pom.xml, addons/web-support/tests/pom.xml, ear/pom.xml, executor/pom.xml, furnace-service-provider/pom.xml, model/pom.xml, pom.xml, services/pom.xml, tests/e2e/pom.xml, tests/pom.xml, tests/test-authentication-client/pom.xml, tests/wildfly-dist/pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml, ui/pom.xml
https://issues.redhat.com/browse/WINDUP-2789
=> WINDUP-2789: change pom version for new release

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-2819
"Analysis results" page => Added the delete icon to the "Actions" column.
=> WINDUP-2819: New PF4 UI : Delete analysis icon under Actions

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-2839
Aligned actions column header to the right
=> WINDUP-2839: [UI] "Actions" header right aligned

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-2836
Added "Question mark" to the cancel dialog of an execution
=> WINDUP-2836: [UI] Missing question mark

ui-pf4/src/main/webapp/src/pages/projects/project-list/project-list.tsx
https://issues.redhat.com/browse/WINDUP-2842
Add truncate to the "Description" column
=> WINDUP-2842: [UI] Kebab menu/dropdown disappear from projects all page

ui-pf4/src/main/webapp/src/components/welcome/tests/__snapshots__/welcome.test.tsx.snap, ui-pf4/src/main/webapp/src/components/welcome/welcome.tsx, ui-pf4/src/main/webapp/src/pages/projects/new-project/new-project.tsx, ui-pf4/src/main/webapp/src/pages/projects/new-project/wizard/project-wizard.tsx, ui-pf4/src/main/webapp/src/pages/projects/project-list/project-list.tsx, ui-pf4/src/main/webapp/src/pages/projects/project-list/tests/project-list.test.tsx
https://issues.redhat.com/browse/WINDUP-2837
Changed "Create Project" by "Create project"
=> WINDUP-2837: [UI] inconsistency in button names

ui-pf4/src/main/webapp/src/components/package-selection/package-selection.tsx
https://issues.redhat.com/browse/WINDUP-2853
Replace "of" by "on". See the screenshot below:
=> WINDUP-2853: Minor change in statement on package wait page " Of needs to be replaced by On"

ui-pf4/src/main/webapp/src/components/advanced-options-form/advanced-options-form.tsx, ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts, ui-pf4/src/main/webapp/src/components/custom-empty-state/custom-empty-state.tsx, ui-pf4/src/main/webapp/src/components/package-selection/package-selection.tsx, ui-pf4/src/main/webapp/src/components/project-details-form/project-details-form.tsx, ui-pf4/src/main/webapp/src/components/rulelabel-server-path-form/rulelabel-server-path-form.tsx, ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx, ui-pf4/src/main/webapp/src/components/transformation-path/transformation-path.tsx, ui-pf4/src/main/webapp/src/components/upload-files-dropzone/upload-files-dropzone.tsx, ui-pf4/src/main/webapp/src/components/welcome/welcome.tsx, ui-pf4/src/main/webapp/src/containers/custom-labels/custom-labels.tsx, ui-pf4/src/main/webapp/src/containers/custom-rules/custom-rules.tsx, ui-pf4/src/main/webapp/src/containers/rule-label-details-modal/rule-label-details-modal.tsx, ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx, ui-pf4/src/main/webapp/src/pages/global-labels/system-provided/system-provided.tsx, ui-pf4/src/main/webapp/src/pages/global-labels/user-provided/user-provided.tsx, ui-pf4/src/main/webapp/src/pages/global-rules/system-provided/system-provided.tsx, ui-pf4/src/main/webapp/src/pages/global-rules/user-provided/user-provided.tsx, ui-pf4/src/main/webapp/src/pages/projects/new-project/new-project.tsx, ui-pf4/src/main/webapp/src/pages/projects/new-project/wizard/project-wizard.tsx
https://issues.redhat.com/browse/WINDUP-2849
Changed grammar and punctuation according to the document attached to the ticket
=> WINDUP-2849: MTA Web UI - PF4 - grammar and punctuation changes

ui-pf4/src/main/webapp/cypress/integration/new-project.spec.js, ui-pf4/src/main/webapp/src/components/add-applications-form/add-applications-serverpath-form.tsx, ui-pf4/src/main/webapp/src/components/add-applications-tabs/add-applications-tabs.tsx
https://issues.redhat.com/browse/WINDUP-2856
Change "Directory path" by "Server path"
=> WINDUP-2856: Change "Directory path" by "Server" path to remark that folder must be on the server host

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-2871
Changed "Issues" by "issues"
=> WINDUP-2871: PF4 Web UI - Analysis Results - All Issues action

ui-pf4/src/main/webapp/src/components/add-applications-form/add-applications-serverpath-form.tsx
https://issues.redhat.com/browse/WINDUP-2898
=> WINDUP-2898: Server path tab's checkbox label

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/active-execution-list.tsx, ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx, ui-pf4/src/main/webapp/src/pages/applications/application-list/application-list.tsx, ui-pf4/src/main/webapp/src/store/executions-ws/selectors.tsx
https://issues.redhat.com/browse/WINDUP-2882
Problem:
Analysis filter does not work for "Running" status.
=> WINDUP-2882: MTA WebUI Issues - Review with PM - fix filter by "running" analysis

ui-pf4/src/main/webapp/src/pages/analysis-configuration/configuration-details/advanced-options/advanced-options.tsx, ui-pf4/src/main/webapp/src/pages/analysis-configuration/configuration-details/general/general.tsx, ui-pf4/src/main/webapp/src/pages/analysis-configuration/configuration-details/packages/packages.tsx, ui-pf4/src/main/webapp/src/pages/projects/project-list/components/edit-project-modal.tsx
https://issues.redhat.com/browse/WINDUP-2892
https://user-images.githubusercontent.com/2582866/104009132-d123b300-51aa-11eb-88c3-83f7e9f7238f.mp4
=> WINDUP-2892: RFE : When no fields are changed while editing a project "Save" and "Save and Run" buttons should be disabled

addons/messaging-executor/addon/pom.xml, addons/messaging-executor/api/pom.xml, addons/messaging-executor/impl/pom.xml, addons/messaging-executor/pom.xml, addons/messaging-executor/tests/pom.xml, addons/pom.xml, addons/web-support/addon/pom.xml, addons/web-support/api/pom.xml, addons/web-support/impl/pom.xml, addons/web-support/pom.xml, addons/web-support/tests/pom.xml, ear/pom.xml, executor/pom.xml, furnace-service-provider/pom.xml, model/pom.xml, pom.xml, services/pom.xml, tests/e2e/pom.xml, tests/pom.xml, tests/test-authentication-client/pom.xml, tests/wildfly-dist/pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml, ui-pf4/pom.xml, ui/pom.xml
Move the artifacts versions of windup from 5.1.5 to 5.2.0
=> upgrade from 5.1.5 to 5.2.0

addons/messaging-executor/addon/pom.xml, addons/messaging-executor/api/pom.xml, addons/messaging-executor/impl/pom.xml, addons/messaging-executor/pom.xml, addons/messaging-executor/tests/pom.xml, addons/pom.xml, addons/web-support/addon/pom.xml, addons/web-support/api/pom.xml, addons/web-support/impl/pom.xml, addons/web-support/pom.xml, addons/web-support/tests/pom.xml, ear/pom.xml, executor/pom.xml, furnace-service-provider/pom.xml, model/pom.xml, pom.xml, services/pom.xml, tests/e2e/pom.xml, tests/pom.xml, tests/test-authentication-client/pom.xml, tests/wildfly-dist/pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml, ui-pf4/pom.xml, ui/pom.xml
https://issues.redhat.com/browse/WINDUP-3115
=> WINDUP-3115 Rollback changes to POMs due to build failure

tsmodelsgen-maven-plugin/pom.xml
https://issues.redhat.com/browse/WINDUP-3164
=> WINDUP-3164: upgrade maven-plugin-plugin version to fix build failure

ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx, ui-pf4/src/main/webapp/src/components/select-card/select-card.tsx
https://issues.redhat.com/browse/WINDUP-3319
Changed transformation path as follows:
=> [WINDUP-3319] - Web UI - Transformation Targets

ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx, ui-pf4/src/main/webapp/src/components/select-card/select-card.tsx
https://issues.redhat.com/browse/WINDUP-3327
Changes should look like:
=> [WINDUP-3327] - MTA Web UI - new Targets screen - "New" wording

ui-pf4/src/main/webapp/src/pages/projects/new-project/review/review.tsx
https://issues.redhat.com/browse/WINDUP-3320
- Exclude Sources from the advanced options
=> [WINDUP-3320] - Improvements to the presentation of the 'Review project details'

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/PackageDiscoveryServiceImpl.java
https://issues.redhat.com/browse/WINDUP-3335
=> [WINDUP-3335-MTA Web - Package Discovery - ignore target folder

pom.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml
Refers to https://github.com/windup/windup/pull/1504
=> Bump Forge 3.10.0.Final

ui-pf4/src/main/webapp/src/layout/ThemeUtils.tsx
https://issues.redhat.com/browse/WINDUP-3461
=> [WINDUP-3461] - The MTR Themes should point to correct links

ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
https://issues.redhat.com/browse/WINDUP-3472
=> [WINDUP-3472] - Web UI - Transformation Targets order and 'New' Label

services/pom.xml, tsmodelsgen-maven-plugin/pom.xml
This depends on https://github.com/windup/windup/pull/1515
=> Managed bootstrap themed artifacts dependencies

ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx, ui-pf4/src/main/webapp/src/layout/ThemeUtils.tsx, ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3478
=> [WINDUP-3478] - MTA/MTR - remove the visibility of the Azure AKS target

tools/graph-tool/pom.xml, ui-pf4/pom.xml, ui-pf4/src/main/webapp/src/components/select-card-gallery/select-card-gallery.tsx
Upgrade to be aligned with https://github.com/windup/windup/pull/1521
=> Upgrade freemarker

pom.xml, services/pom.xml, tsmodelsgen-maven-plugin/pom.xml
depends on https://github.com/windup/windup/pull/1554
=> Dependencies updates

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
This adds a new Azure service. I'm also setting up the rules for Azure Container Apps
=> Adds Azure Container Apps option

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-3514
=> [WINDUP-3514] - Upgrade minimatch

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-3546
=> [WINDUP-3546] - Upgrade loader-utils

ui-pf4/src/main/webapp/src/containers/add-rule-label-button/add-rule-label-button.tsx, ui-pf4/src/main/webapp/src/containers/custom-labels/custom-labels.tsx, ui-pf4/src/main/webapp/src/containers/custom-rules/custom-rules.tsx
https://issues.redhat.com/browse/WINDUP-3322
Back porting: https://github.com/windup/windup-web/pull/825
=> [WINDUP-3322] - Neither "Save" nor "Save and Run" is enabled when some change is made in Custom rule or custom labels

.github/workflows/backport.yml
Based on https://github.com/windup/windup-rulesets/pull/796
=> Add backport github workflow

services/src/main/java/org/jboss/windup/web/services/rest/LabelEndpointImpl.java, services/src/main/java/org/jboss/windup/web/services/rest/RuleEndpointImpl.java
Backport https://github.com/windup/windup-web/pull/823
=> [WINDUP-3356] - Duplicating Custom rules and Custom labels

pom.xml, services/pom.xml, tools/graph-tool/pom.xml, ui-pf4/pom.xml
https://issues.redhat.com/browse/WINDUP-3681
=> [WINDUP-3681] - Upgrade maven-war-plugin

.github/workflows/pr_build_jdk11.yaml
=> Enhance GH Jobs to build all Windup dependencies

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-3678
=> [WINDUP-3678] - Analysis search by ID/status does not work with extra spaces.

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3717
=> Removed 'New' label from OpenJDK and Azure targets

ui-pf4/src/main/webapp/src/Constants.tsx, ui-pf4/src/main/webapp/src/components/advanced-options-form/advanced-options-form.tsx, ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts
https://issues.redhat.com/browse/WINDUP-3735
=> WINDUP-3735 Added 'skipSourceCodeReports' advanced option

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java
https://issues.redhat.com/browse/WINDUP-3748
depends on https://github.com/windup/windup/pull/1613
=> WINDUP-3748 Delete graph folder at the end of an analysis

model/src/main/java/org/jboss/windup/web/services/model/WindupExecution.java, services/src/main/java/org/jboss/windup/web/services/servlet/FileDefaultServletFilter.java, services/src/main/webapp/WEB-INF/web.xml, ui-pf4/src/main/webapp/src/Constants.tsx, ui-pf4/src/main/webapp/src/components/advanced-options-form/advanced-options-form.tsx, ui-pf4/src/main/webapp/src/components/advanced-options-form/schema.ts
https://issues.redhat.com/browse/WINDUP-3561
Required PRs:
- https://github.com/windup/windup/pull/1579
- https://github.com/windup/windup-distribution/pull/101
=> [WINDUP-3561] - Update static reports to PF4 - mandatory reports

addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/services/WindupExecutorServiceImpl.java, pom.xml, services/src/test/resources/arquillian.xml, tests/wildfly-dist/pom.xml, tests/wildfly-dist/src/main/resources/keycloak_config/standalone-full.xml
https://issues.redhat.com/browse/WINDUP-3602
```
mvn install:install-file -Dfile=jboss-eap-7.4.9.zip \
-DgroupId=jboss-eap \
-DartifactId=jboss-eap-dist -Dversion=7.4.9.GA \
-Dpackaging=zip
```
> `jboss-eap-7.4.9.zip` is the distribution zip file that belongs to EAP.
- Compile the entire project:
```
mvn clean install -DskipTests
```
- Generate the Distribution based on EAP
```
mvn clean install -DskipTests -f tests \
-Dwildfly-dist.groupId=jboss-eap \
-Dwildfly-dist.artifactId=jboss-eap-dist \
-Dversion.wildfly-dist=7.4.9.GA \
-Dwildfly-dist.content-zip-name=jboss-eap-7.4
```
Make sure you have JDk11 in your terminal and then:
```
mvn test -f addons
mvn test -f services
```
Make sure you have JDk17 in your terminal and then:
```
mvn test -f addons
mvn test -f services
```
=> WINDUP-3602 Support for jdk17-eap7 testing

ui-pf4/src/main/webapp/src/pages/analysis-results/execution-list/execution-list.tsx
https://issues.redhat.com/browse/WINDUP-3795
=> WINDUP-3795 'Download ZIP report' typo

pom.xml
https://issues.redhat.com/browse/WINDUP-3841
=> WINDUP-3841: jackson-databind CVE fix

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3846
=> WINDUP-3846 Typo 'supported'

ui-pf4/src/main/webapp/src/components/select-card/select-card.tsx, ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/projects/WINDUP/issues/WINDUP-3900
=> [WINDUP-3900] - Web UI Transformation Targets - Camel Rules

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3954
=> [WINDUP-3954] - Jakarta EE Transformation Target wording

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-3943
=> [WINDUP-3943] - JBoss Web Server 6 - fix typo

ui-pf4/src/main/webapp/src/layout/TransformationPaths.ts
https://issues.redhat.com/browse/WINDUP-4090
=> [WINDUP-4090] - Changes to Web Console to expose Camel 4.1 Rules

pom.xml
upgrade test keycloak in windup-web for CVE
=> WINDUP-3772

docker-web-builder/settings.xml, pom.xml, settings.xml, tsmodelsgen-invocation/pom.xml, tsmodelsgen-maven-plugin/pom.xml
https://issues.sonatype.org/browse/OSSRH-96863
=> Move to s01.oss.sonatype.org Sonatype repository

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-4117
=> [WINDUP-4117] - Upgrade follow-redirects

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-3958
=> [WINDUP-3958] - Upgrade tough-cookie

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-3963
=> [WINDUP-3963] - Upgrade semver

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-4152
=> WINDUP-4152:upgrade follow-redirects to 1.15.6

ui-pf4/src/main/webapp/package.json, ui-pf4/src/main/webapp/yarn.lock
https://issues.redhat.com/browse/WINDUP-4115
https://issues.redhat.com/browse/WINDUP-4098
https://bugzilla.redhat.com/show_bug.cgi?id=2254559
=> WINDUP-4115 CVE upgrade css-tools
